### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by motokocc** [aptos-labs/aptos-core#1033]
# 🐛 Bug

run validator failed!!!

**Stack trace/error message**
```
ubuntu@VM-0-5-ubuntu:~/aptos-core$ RUST_BACKTRACE=1 cargo run -p aptos-node --release -- -f ~/$WORKSPACE/validator.yaml
    Finished release [optimized + debuginfo] target(s) in 0.52s
     Running `target/release/aptos-node -f /home/ubuntu/testnet/validator.yaml`
thread 'main' panicked at 'Failed to load node config: IO("genesis", Os { code: 2, kind: NotFound, message: "No such file or directory" })', aptos-node/src/main.rs:75:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::expect
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23
   4: aptos_node::main
             at ./aptos-node/src/main.rs:75:22
   5: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
`
thread 'main' panicked at 'Failed to load node config: IO("genesis", Os { code: 2, kind: NotFound, message: "No such file or directory" })', aptos-node/src/main.rs:75:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

## System information

**Please complete the following information:**
- 
(https://github.com/aptos-labs/aptos-core/commit/1bd3c5838b8b27e37e6f0fdfbd62885e125f086b)
- 
rustc 1.60.0 (7737e0b5c 2022-04-04)
- 
 ubuntu 20.04

## Additional context

![图片](https://user-images.githubusercontent.com/80674620/168777393-c7f89395-bb70-4ba3-bf20-a2357769a1d5.png)

**Comment by motokocc** [comment]
> 

thank you ser， this is my fault， config wrong
