### ISSUE TITLE
[Bug] node crush when start (version aptos-node-v1.7.3)

### ISSUE THREAD

**Issue by nolanxyg** [aptos-labs/aptos-core#10597]
# 🐛 Bug

node crush when start (version aptos-node-v1.7.3)

## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
just doing upgrade to aptos-node-v1.7.3, node crushed when start
```

**Stack trace/error message**
```
details = "panicked at 'Failed to truncate ledger db.: aptos_types::transaction::Transaction iterator: first version 301722169, expecting version 301722169, got 301722681 from underlying iterator.', storage/aptosdb/src/state_store/mod.rs:404:18"
backtrace = """
   0:     0x556f4a170603 - backtrace::backtrace::libunwind::trace::h4369f289182196ea
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h56cee1777861dd1d
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h0a55656dbdef2ae2
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/backtrace/mod.rs:53:14
                           backtrace::capture::Backtrace::create::h7e8e12d9ae81ffc9
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/capture.rs:176:9
   1:     0x556f4a170541 - backtrace::capture::Backtrace::new::h49aeea9a4cc656f2
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x556f47aa2cb4 - aptos_crash_handler::handle_panic::hae483e406b07f321
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:37:38
                           aptos_crash_handler::setup_panic_handler::{{closure}}::ha1f099cb12869921
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:29:9
   3:     0x556f4a28d13d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::ha1f76bdae3c27ab6
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1999:9
                           std::panicking::rust_panic_with_hook::h45f66047b14c555c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:709:13
   4:     0x556f4a28ced7 - std::panicking::begin_panic_handler::{{closure}}::h49d1a88ef0908eb4
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:597:13
   5:     0x556f4a28bbd6 - std::sys_common::backtrace::__rust_end_short_backtrace::hccebf9e57f8cc425
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:151:18
   6:     0x556f4a28cc22 - rust_begin_unwind
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   7:     0x556f4a2b3cb3 - core::panicking::panic_fmt::h54ec9d0e3180a83d
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   8:     0x556f4a2b4153 - core::result::unwrap_failed::h1cd730365d65235f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
   9:     0x556f47e72d9d - core::result::Result<T,E>::expect::hd9572db1164c3f5f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1033:23
                           aptos_db::state_store::StateStore::sync_commit_progress::h51ca8e7d7253c7d0
                               at /usr/src/indexer-node/storage/aptosdb/src/state_store/mod.rs:403:13
  10:     0x556f47e72264 - aptos_db::state_store::StateStore::new::hd6c00681b63d30d4
                               at /usr/src/indexer-node/storage/aptosdb/src/state_store/mod.rs:317:13
  11:     0x556f47dcc11b - aptos_db::AptosDB::new_with_dbs::h893ba2179f79ea59
                               at /usr/src/indexer-node/storage/aptosdb/src/lib.rs:313:36
  12:     0x556f476e115d - aptos_db::AptosDB::open_internal::h696a5644673978b5
                               at /usr/src/indexer-node/storage/aptosdb/src/lib.rs:371:26
2023-10-20T05:42:05.178089Z [main] INFO aptos-node/src/lib.rs:463 Using node config NodeConfig { api: ApiConfig { enabled: true, address: 0.0.0.0:8080, tls_cert_path: None, tls_key_path: None, content_length_limit: None, failpoints_enabled: false, json_output_enabled: true, bcs_output_enabled: true, encode_submission_enabled: true, transaction_submission_enabled: true, transaction_simulation_enabled: true, max_submit_transaction_batch_size: 10, max_transactions_page_size: 100, max_events_page_size: 100, max_account_resources_page_size: 9999, max_account_modules_page_size: 9999, max_gas_view_function: 2000000, max_runtime_workers: None, runtime_worker_multiplier: 2, gas_estimation: GasEstimationConfig { enabled: true, static_override: None, full_block_txns: 250, low_block_history: 10, market_block_history: 30, aggressive_block_history: 120, cache_expiration_ms: 500 } }, base: BaseConfig { data_dir: "/opt/aptos/data", working_dir: None, role: full_node, waypoint: FromFile("/opt/aptos/genesis/waypoint.txt") }, consensus: ConsensusConfig { max_network_channel_size: 1024, max_sending_block_txns: 2500, max_sending_block_txns_quorum_store_override: 4000, max_sending_block_bytes: 614400, max_sending_block_bytes_quorum_store_override: 5242880, max_receiving_block_txns: 10000, max_receiving_block_txns_quorum_store_override: 10000, max_receiving_block_bytes: 3145728, max_receiving_block_bytes_quorum_store_override: 6291456, max_pruned_blocks_in_mem: 100, mempool_executed_txn_timeout_ms: 1000, mempool_txn_pull_timeout_ms: 1000, round_initial_timeout_ms: 1500, round_timeout_backoff_exponent_base: 1.2, round_timeout_backoff_max_exponent: 6, safety_rules: SafetyRulesConfig { backend: InMemoryStorage, logger: LoggerConfig { chan_size: 10000, enable_backtrace: false, is_async: true, level: Info, enable_telemetry_remote_log: true, enable_telemetry_flush: true, telemetry_level: Error, tokio_console_port: None }, service: Local, test: None, network_timeout_ms: 30000, enable_cached_safety_data: true, initial_safety_rules_config: None }, sync_only: false, channel_size: 30, quorum_store_pull_timeout_ms: 400, quorum_store_poll_time_ms: 300, wait_for_full_blocks_above_pending_blocks: 100, wait_for_full_blocks_above_recent_fill_threshold: 1.1, intra_consensus_channel_buffer_size: 10, quorum_store: QuorumStoreConfig { channel_size: 1000, proof_timeout_ms: 10000, batch_generation_poll_interval_ms: 25, batch_generation_min_non_empty_interval_ms: 200, batch_generation_max_interval_ms: 250, sender_max_batch_txns: 250, sender_max_batch_bytes: 1048576, sender_max_num_batches: 20, sender_max_total_txns: 2000, sender_max_total_bytes: 4194304, receiver_max_batch_txns: 250, receiver_max_batch_bytes: 1048576, receiver_max_num_batches: 20, receiver_max_total_txns: 2000, receiver_max_total_bytes: 4194304, batch_request_num_peers: 5, batch_request_retry_limit: 10, batch_request_retry_interval_ms: 1000, batch_request_rpc_timeout_ms: 5000, batch_expiry_gap_when_init_usecs: 60000000, memory_quota: 120000000, db_quota: 300000000, batch_quota: 300000, mempool_txn_pull_max_bytes: 4194304, back_pressure: QuorumStoreBackPressureConfig { backlog_txn_limit_count: 12000, backlog_per_validator_batch_limit_count: 4, decrease_duration_ms: 1000, increase_duration_ms: 1000, decrease_fraction: 0.5, dynamic_min_txn_per_s: 160, dynamic_max_txn_per_s: 2000 }, num_workers_for_remote_batches: 10, batch_buckets: [0, 150, 300, 500, 1000, 3000, 5000, 10000, 100000, 1000000] }, vote_back_pressure_limit: 30, pipeline_backpressure: [PipelineBackpressureValues { back_pressure_pipeline_latency_limit_ms: 1000, max_sending_block_txns_override: 10000, max_sending_block_bytes_override: 5242880, backpressure_proposal_delay_ms: 100 }, PipelineBackpressureValues { back_pressure_pipeline_latency_limit_ms: 1500, max_sending_block_txns_override: 10000, max_sending_block_bytes_override: 5242880, backpressure_proposal_delay_ms: 200 }, PipelineBackpressureValues { back_pressure_pipeline_latency_limit_ms: 2000, max_sending_block_txns_override: 10000, max_sending_block_bytes_override: 5242880, backpressure_proposal_delay_ms: 300 }, PipelineBackpressureValues { back_pressure_pipeline_latency_limit_ms: 2500, max_sending_block_txns_override: 2000, max_sending_block_bytes_override: 1048576, backpressure_proposal_delay_ms: 300 }, PipelineBackpressureValues { back_pressure_pipeline_latency_limit_ms: 4000, max_sending_block_txns_override: 500, max_sending_block_bytes_override: 1048576, backpressure_proposal_delay_ms: 300 }], window_for_chain_health: 100, chain_health_backoff: [ChainHealthBackoffValues { backoff_if_below_participating_voting_power_percentage: 80, max_sending_block_txns_override: 10000, max_sending_block_bytes_override: 5242880, backoff_proposal_delay_ms: 150 }, ChainHealthBackoffValues { backoff_if_below_participating_voting_power_percentage: 77, max_sending_block_txns_override: 2000, max_sending_block_bytes_override: 1048576, backoff_proposal_delay_ms: 300 }, ChainHealthBackoffValues { backoff_if_below_participating_voting_power_percentage: 75, max_sending_block_txns_override: 1000, max_sending_block_bytes_override: 1048576, backoff_proposal_delay_ms: 300 }, ChainHealthBackoffValues { backoff_if_below_participating_voting_power_percentage: 72, max_sending_block_txns_override: 500, max_sending_block_bytes_override: 1048576, backoff_proposal_delay_ms: 300 }, ChainHealthBackoffValues { backoff_if_below_participating_voting_power_percentage: 69, max_sending_block_txns_override: 250, max_sending_block_bytes_override: 1048576, backoff_proposal_delay_ms: 300 }] }, execution: ExecutionConfig { genesis: Some(...), genesis_file_location: "/opt/aptos/genesis/genesis.blob" , failpoints: None, full_node_networks: [NetworkConfig { max_connection_delay_ms: 60000, connection_backoff_base: 2, connectivity_check_interval_ms: 5000, network_channel_size: 1024, max_concurrent_network_reqs: 100, discovery_method: Onchain, discovery_methods: [], identity: FromConfig(IdentityFromConfig { key: ConfigKey { key: <elided secret for PrivateKey> }, peer_id: b3ff4a436dbef3d76555933d8010c7c0e8264a7883bcee9f9fd6aba6691a511b }), listen_address: /ip4/0.0.0.0/tcp/6182, mutual_authentication: false, network_id: Public, runtime_threads: None, inbound_rx_buffer_size_bytes: Some(3145728), inbound_tx_buffer_size_bytes: Some(524288), outbound_rx_buffer_size_bytes: Some(3145728), outbound_tx_buffer_size_bytes: Some(1048576), seed_addrs: {}, seeds: {b6efef1ce4bb0245a169b5fe15ae186eb84b176023d789f51d0deb5661c68b42: Peer { addresses: [/dns4/aptos-mainnet-node-0.nodereal.io/tcp/6182/noise-ik/0xb6efef1ce4bb0245a169b5fe15ae186eb84b176023d789f51d0deb5661c68b42/handshake/0], keys: {}, role: upstream_peer }}, max_frame_size: 4194304, enable_proxy_protocol: false, ping_interval_ms: 10000, ping_timeout_ms: 20000, ping_failures_tolerated: 3, max_outbound_connections: 50, max_inbound_connections: 50, inbound_rate_limit_config: None, outbound_rate_limit_config: None, max_message_size: 67108864, max_parallel_deserialization_tasks: Some(4) }], indexer: IndexerConfig { enabled: true, postgres_uri: Some("postgresql://aptos:*@tf-nodereal-qa-aptos.cluster-cb6vaj1ctcqk.us-east-1.rds.amazonaws.com/mainnet-indexer"), processor: Some("nr_txn_processor"), starting_version: None, skip_migrations: Some(false), check_chain_id: Some(true), batch_size: Some(500), fetch_tasks: Some(5), processor_tasks: Some(5), emit_every: Some(10000), gap_lookback_versions: Some(1500000), ans_contract_address: None, nft_points_contract: None }, indexer_grpc: IndexerGrpcConfig { enabled: false, address: None, processor_task_count: None, processor_batch_size: None, output_batch_size: None }, inspection_service: InspectionServiceConfig { address: "0.0.0.0", port: 9101, expose_configuration: false, expose_peer_information: true, expose_system_information: true }, logger: LoggerConfig { chan_size: 10000, enable_backtrace: false, is_async: true, level: Info, enable_telemetry_remote_log: true, enable_telemetry_flush: true, telemetry_level: Error, tokio_console_port: None }, mempool: MempoolConfig { capacity: 2000000, capacity_bytes: 2147483648, capacity_per_user: 100, default_failovers: 1, max_broadcasts_per_peer: 20, max_network_channel_size: 1024, mempool_snapshot_interval_secs: 180, shared_mempool_ack_timeout_ms: 2000, shared_mempool_backoff_interval_ms: 30000, shared_mempool_batch_size: 300, shared_mempool_max_batch_bytes: 64880640, shared_mempool_max_concurrent_inbound_syncs: 4, shared_mempool_tick_interval_ms: 50, shared_mempool_peer_update_interval_ms: 1000, system_transaction_timeout_secs: 600, system_transaction_gc_interval_ms: 60000, broadcast_buckets: [0, 150, 300, 500, 1000, 3000, 5000, 10000, 100000, 1000000], eager_expire_threshold_ms: Some(10000), eager_expire_time_ms: 3000 }, peer_monitoring_service: PeerMonitoringServiceConfig { enable_peer_monitoring_client: true, latency_monitoring: LatencyMonitoringConfig { latency_ping_interval_ms: 30000, latency_ping_timeout_ms: 20000, max_latency_ping_failures: 3, max_num_latency_pings_to_retain: 10 }, max_concurrent_requests: 1000, max_network_channel_size: 1000, max_num_response_bytes: 102400, max_request_jitter_ms: 1000, metadata_update_interval_ms: 5000, network_monitoring: NetworkMonitoringConfig { network_info_request_interval_ms: 60000, network_info_request_timeout_ms: 10000 }, node_monitoring: NodeMonitoringConfig { node_info_request_interval_ms: 20000, node_info_request_timeout_ms: 10000 }, peer_monitor_interval_usec: 1000000, performance_monitoring: PerformanceMonitoringConfig { enable_direct_send_testing: false, direct_send_data_size: 524288, direct_send_interval_usec: 2000000, enable_rpc_testing: false, rpc_data_size: 524288, rpc_interval_usec: 2000000, rpc_timeout_ms: 10000 } }, state_sync: StateSyncConfig { data_streaming_service: DataStreamingServiceConfig { global_summary_refresh_interval_ms: 50, max_concurrent_requests: 6, max_concurrent_state_requests: 6, max_data_stream_channel_sizes: 300, max_request_retry: 5, max_notification_id_mappings: 300, progress_check_interval_ms: 50 }, aptos_data_client: AptosDataClientConfig { latency_monitor_loop_interval_ms: 50, max_epoch_chunk_size: 200, max_num_in_flight_priority_polls: 10, max_num_in_flight_regular_polls: 10, max_num_output_reductions: 0, max_optimistic_fetch_version_lag: 50000, max_response_timeout_ms: 60000, max_state_chunk_size: 4000, max_subscription_version_lag: 100000, max_transaction_chunk_size: 2000, max_transaction_output_chunk_size: 1000, optimistic_fetch_timeout_ms: 5000, response_timeout_ms: 10000, summary_poll_loop_interval_ms: 200, use_compression: true }, state_sync_driver: StateSyncDriverConfig { bootstrapping_mode: ExecuteOrApplyFromGenesis, commit_notification_timeout_ms: 5000, continuous_syncing_mode: ExecuteTransactionsOrApplyOutputs, enable_auto_bootstrapping: false, fallback_to_output_syncing_secs: 180, progress_check_interval_ms: 50, max_connection_deadline_secs: 10, max_consecutive_stream_notifications: 10, max_num_stream_timeouts: 12, max_pending_data_chunks: 100, max_stream_wait_time_ms: 5000, mempool_commit_ack_timeout_ms: 5000, num_versions_to_skip_snapshot_sync: 100000000 }, storage_service: StorageServiceConfig { max_concurrent_requests: 4000, max_epoch_chunk_size: 200, max_invalid_requests_per_peer: 500, max_lru_cache_size: 500, max_network_channel_size: 4000, max_network_chunk_bytes: 4194304, max_num_active_subscriptions: 30, max_optimistic_fetch_period_ms: 5000, max_state_chunk_size: 4000, max_subscription_period_ms: 30000, max_transaction_chunk_size: 2000, max_transaction_output_chunk_size: 1000, min_time_to_ignore_peers_secs: 300, request_moderator_refresh_interval_ms: 1000, storage_summary_refresh_interval_ms: 100 } }, storage: StorageConfig { backup_service_address: 0.0.0.0:6186, dir: "db", storage_pruner_config: PrunerConfig { ledger_pruner_config: LedgerPrunerConfig { enable: false, prune_window: 150000000, batch_size: 500, user_pruning_window_offset: 200000 }, state_merkle_pruner_config: StateMerklePrunerConfig { enable: true, prune_window: 1000000, batch_size: 1000 }, epoch_snapshot_pruner_config: EpochSnapshotPrunerConfig { enable: true, prune_window: 80000000, batch_size: 1000 } }, data_dir: "/opt/aptos/data", buffered_state_target_items: 100000, max_num_nodes_per_lru_cache_shard: 8192, rocksdb_configs: RocksdbConfigs { ledger_db_config: RocksdbConfig { max_open_files: 5000, max_total_wal_size: 1073741824, max_background_jobs: 16, block_cache_size: 8388608, block_size: 4096, cache_index_and_filter_blocks: false }, state_merkle_db_config: RocksdbConfig { max_open_files: 5000, max_total_wal_size: 1073741824, max_background_jobs: 16, block_cache_size: 8388608, block_size: 4096, cache_index_and_filter_blocks: false }, use_sharded_state_merkle_db: false, split_ledger_db: false, skip_index_and_usage: false, state_kv_db_config: RocksdbConfig { max_open_files: 5000, max_total_wal_size: 1073741824, max_background_jobs: 16, block_cache_size: 8388608, block_size: 4096, cache_index_and_filter_blocks: false }, index_db_config: RocksdbConfig { max_open_files: 1000, max_total_wal_size: 1073741824, max_background_jobs: 16, block_cache_size: 8388608, block_size: 4096, cache_index_and_filter_blocks: false } }, enable_indexer: true }, validator_network: None }
2023-10-20T05:42:05.440411Z [main] INFO storage/schemadb/src/lib.rs:169 Opened RocksDB. {"rocksdb_name":"ledger_db"}
2023-10-20T05:42:05.440439Z [main] INFO storage/aptosdb/src/ledger_db.rs:312 Opened ledger_db at "/opt/aptos/data/db/ledger_db"!
2023-10-20T05:42:05.440441Z [main] INFO storage/aptosdb/src/ledger_db.rs:97 Opened ledger metadata db! {"ledger_metadata_db_path":"/opt/aptos/data/db/ledger_db"}
2023-10-20T05:42:05.440442Z [main] INFO storage/aptosdb/src/ledger_db.rs:103 Individual ledger dbs are not enabled!
2023-10-20T05:42:05.440444Z [main] INFO storage/aptosdb/src/state_kv_db.rs:43 State K/V DB is not enabled!
2023-10-20T05:42:05.442403Z [main] INFO storage/aptosdb/src/state_merkle_db.rs:91 Sharded state merkle DB is not enabled!
2023-10-20T05:42:05.468497Z [main] INFO storage/schemadb/src/lib.rs:169 Opened RocksDB. {"rocksdb_name":"state_merkle_db"}
2023-10-20T05:42:05.468535Z [main] INFO storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs:132 Initializing... {"name":"state_merkle_pruner"}
2023-10-20T05:42:05.468599Z [main] INFO storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs:137 Created state_merkle_pruner metadata pruner, start catching up all shards. {"metadata_progress":300687781}
2023-10-20T05:42:05.468607Z [main] INFO storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs:166 Initialized. {"name":"state_merkle_pruner","progress":300687781}
2023-10-20T05:42:05.468698Z [main] INFO storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs:132 Initializing... {"name":"epoch_snapshot_pruner"}
2023-10-20T05:42:05.468706Z [main] INFO storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs:137 Created epoch_snapshot_pruner metadata pruner, start catching up all shards. {"metadata_progress":221708306}
2023-10-20T05:42:05.468708Z [main] INFO storage/aptosdb/src/pruner/state_merkle_pruner/mod.rs:166 Initialized. {"name":"epoch_snapshot_pruner","progress":221708306}
2023-10-20T05:42:05.468810Z [main] INFO storage/aptosdb/src/state_store/mod.rs:373 Start syncing databases... {"overall_commit_progress":301722168}
2023-10-20T05:42:05.468821Z [main] INFO storage/aptosdb/src/state_store/mod.rs:394 Attempt ledger truncation... {"ledger_commit_progress":301722168}
  13:     0x556f47811381 - aptos_db::AptosDB::open::h928d36199b3b22d1
                               at /usr/src/indexer-node/storage/aptosdb/src/lib.rs:398:9
                           aptos_node::storage::initialize_database_and_checkpoints::ha77975b570e3a408
                               at /usr/src/indexer-node/aptos-node/src/storage.rs:99:20
  14:     0x556f475d385d - aptos_node::setup_environment_and_start_node::haf3853269ce42a95
                               at /usr/src/indexer-node/aptos-node/src/lib.rs:471:9
  15:     0x556f475d2488 - aptos_node::start::h04ab0cc4231650a0
                               at /usr/src/indexer-node/aptos-node/src/lib.rs:216:9
  16:     0x556f475cf944 - aptos_node::AptosNodeArgs::run::h1e21da680a9f960e
                               at /usr/src/indexer-node/aptos-node/src/lib.rs:153:13
  17:     0x556f4750b2d6 - aptos_node::main::h62ea7adc5635d967
                               at /usr/src/indexer-node/aptos-node/src/main.rs:19:5
  18:     0x556f4750c316 - core::ops::function::FnOnce::call_once::hfd8a39a16b9c1a8f
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
                           std::sys_common::backtrace::__rust_begin_short_backtrace::h1c3229793d4243d1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/sys_common/backtrace.rs:135:18
  19:     0x556f4750c32c - std::rt::lang_start::{{closure}}::h5e1a755f53c2eb61
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:166:18
  20:     0x556f4a27f7e5 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h802b0fdd426a12ca
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:284:13
                           std::panicking::try::do_call::h2a2f25050efa0cf8
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
                           std::panicking::try::h9ca7f841c0f0e3dd
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
                           std::panic::catch_unwind::h92d42a62587f8121
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
                           std::rt::lang_start_internal::{{closure}}::hf1926c7a173d562c
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:48
                           std::panicking::try::do_call::haac70d88f0cce898
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:500:40
                           std::panicking::try::h5c20719e1031e74b
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:464:19
                           std::panic::catch_unwind::h9b15b36860d5fe4a
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panic.rs:142:14
                           std::rt::lang_start_internal::hf502095b101390bb
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/rt.rs:148:20
  21:     0x556f4750b3f4 - main
  22:     0x7fed8358ed0a - __libc_start_main
  23:     0x556f475091aa - _start
  24:                0x0 - <unknown>
"""

[Logging] Unable to flush recv: timed out waiting on channel
Timed out flushing telemetry: timed out waiting on channel

```

## System information

**Please complete the following information:**
- Aptos Core Version:  aptos-node-v1.7.3
- Rust Version
- Computer OS

**Comment by lbmeiyi** [comment]
Are you still having this issue?

**Comment by lbmeiyi** [comment]
This should be resolved after checking with @michelle-aptos. Closing it out. Thank you!

**Comment by lookisr** [comment]
How did you resolved problem?
