### ISSUE TITLE
Failed when installing aptos CLI with cargo

### ISSUE THREAD

**Issue by lin-yuxiang** [aptos-labs/aptos-core#1064]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
failed to install aptos cli from command: RUST_BACKTRACE=full cargo install --git https://github.com/aptos-labs/aptos-core.git aptos --tag aptos-cli-latest
```

**Stack trace/error message**
```
...
Compiling yaml-rust v0.4.5
   Compiling pretty v0.10.0
   Compiling tint v1.0.1
error: failed to run custom build command for `aptos-metrics v0.1.0 (/home/lin/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/992073a/crates/aptos-metrics)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installheF0ml/release/build/aptos-metrics-bfc22e79d42716f7/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=../../.git/index

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/aptos-metrics/build.rs:17:14
  stack backtrace:
     0:     0x55c45898d30d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x55c45898d30d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55c45898d30d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x55c45898d30d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x55c4589ad15c - core::fmt::write::he803f0f418caf762
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
     5:     0x55c4589896e8 - std::io::Write::write_fmt::h70bc45872f37e7bb
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
     6:     0x55c45898efa7 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x55c45898efa7 - std::sys_common::backtrace::print::h359300b4a7fccf65
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x55c45898efa7 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
     9:     0x55c45898ec70 - std::panicking::default_hook::h03ca0f22e1d2d25e
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
    10:     0x55c45898f6f9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
    11:     0x55c45898f3e7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
    12:     0x55c45898d7d4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x55c45898f0f9 - rust_begin_unwind
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
    14:     0x55c45896da43 - core::panicking::panic_fmt::he1bbc7336d49a357
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
    15:     0x55c45896dad3 - core::result::unwrap_failed::h719f957ed74f93fd
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
    16:     0x55c4589751ca - core::result::Result<T,E>::unwrap::haa76d7a4fd94fe5a
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1065:23
    17:     0x55c458973bc2 - build_script_build::main::hcc710afac098e48a
                                 at /home/lin/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/992073a/crates/aptos-metrics/build.rs:14:22
    18:     0x55c45897414b - core::ops::function::FnOnce::call_once::h9de36027446d5a25
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
    19:     0x55c4589752de - std::sys_common::backtrace::__rust_begin_short_backtrace::h34822afadf79506d
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
    20:     0x55c458973781 - std::rt::lang_start::{{closure}}::hc96979c017f2396d
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:145:18
    21:     0x55c45898c9f1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
    22:     0x55c45898c9f1 - std::panicking::try::do_call::h7bc9dc436daeb8c7
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
    23:     0x55c45898c9f1 - std::panicking::try::h653d68a27ff5f175
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
    24:     0x55c45898c9f1 - std::panic::catch_unwind::h9d739f9f59895e68
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
    25:     0x55c45898c9f1 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
    26:     0x55c45898c9f1 - std::panicking::try::do_call::hfb39d6df61a2e69f
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
    27:     0x55c45898c9f1 - std::panicking::try::h13e2d225134958ac
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
    28:     0x55c45898c9f1 - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
    29:     0x55c45898c9f1 - std::rt::lang_start_internal::h2ba92edce36c035e
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
    30:     0x55c458973750 - std::rt::lang_start::h96d13453ad0a01c7
                                 at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:144:17
    31:     0x55c4589740dc - main
    32:     0x7fbd1de91c87 - __libc_start_main
                                 at /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310
    33:     0x55c45896e1ca - _start
    34:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: failed to compile `aptos v0.1.0 (https://github.com/aptos-labs/aptos-core.git?tag=aptos-cli-v0.1.0#992073ac)`, intermediate artifacts can be found at `/tmp/cargo-installheF0ml`

Caused by:
  build failed
```

## System information

**Please complete the following information:**
-   aptos-cli-latest
-  
-  Ubuntu 18.04

**Comment by davidiw** [comment]
Ubuntu 18.04 is unsupported, could you please retry with Ubuntu 20.04 and running the dev setup script?

Closing to call attention.
