### ISSUE TITLE
[Bug][Compiler-v2] memory quota test failed for the compiler v2

### ISSUE THREAD

**Issue by rahxephon89** [aptos-labs/aptos-core#11566]
# 🐛 Bug

The compiler v2 failed the e2e-move test [clone_large_vectors](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/e2e-move-tests/src/tests/memory_quota.rs#L47) and [add_vec_to_table](https://github.com/aptos-labs/aptos-core/blob/f46e51e45823cd8a8cb8524e5c8d3a8122933d59/aptos-move/e2e-move-tests/src/tests/memory_quota.rs#L75) with the error message:

```
---- tests::memory_quota::clone_large_vectors stdout ----
Compiling, may take a little while to download git dependencies...
result:Keep(ExecutionFailure { location: 000000000000000000000000000000000000000000000000000000000000beef::test, function: 1, code_offset: 39 })
thread 'tests::memory_quota::clone_large_vectors' panicked at aptos-move/e2e-move-tests/src/tests/memory_quota.rs:61:5:
assertion `left == right` failed
  left: Keep(ExecutionFailure { location: 000000000000000000000000000000000000000000000000000000000000beef::test, function: 1, code_offset: 39 })
 right: Keep(Success)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
---- tests::memory_quota::add_vec_to_table stdout ----
Compiling, may take a little while to download git dependencies...
thread 'tests::memory_quota::add_vec_to_table' panicked at aptos-move/e2e-move-tests/src/tests/memory_quota.rs:92:5:
assertion failed: matches!(result, TransactionStatus ::\n    Keep(ExecutionStatus :: MoveAbort { .. }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rahxephon89** [comment]
The error is raised in this function:

```
    public entry fun just_under_quota() {
        let v = vector::empty();
        let t = vector::empty();
        let i = 0;
        while (i < 1000) {
            vector::push_back(&mut v, 0u128);
            i = i + 1;
        };

        i = 0;
        while (i < 622) {
            vector::push_back(&mut t, copy v);
            i = i + 1;
        }
    }
```

If we reduce the upper bound of the condition in the second while loop from 622 to 311 or below, the error will disappear.
