### ISSUE TITLE
[Bug][move-compiler-v1] Cases for V1 panic

### ISSUE THREAD

**Issue by zzjas** [aptos-labs/aptos-core#14095]
# 🐛 Bug

```
module 0xCAFE::Module0 {
    public fun function0<T0: drop, T1: drop + store, T2: copy + drop + store> (var0: T2): T2 {
        if ((var0 == if (true)  { var0 } else { var0 }))  {
        } else {
            var0 = var0;
        };
        var0
    }
}
```

Compiling with V1 will cause:
```
thread 'main' panicked at third_party/move/move-compiler/src/to_bytecode/optimize/remove_fallthrough_jumps.rs:40:36:
called `Option::unwrap()` on a `None` value
```

**Comment by zzjas** [comment]
# 🐛 Bug

```
module 0xCAFE::Module0 {
    public fun function5() {
        let x = &mut 0u8;
        let y = x;
        (copy y != if (false) { y } else { x });
    }
}
```

Compiling with V1 will cause:
```
thread 'main' panicked at third_party/move/move-compiler/src/cfgir/borrows/mod.rs:273:17:
ICE eq freezing failed
```

**Comment by zzjas** [comment]
# 🐛 Bug

```
module 0xCAFE::Module0 {
    public fun f(x: u16, y: &u16) {
        if (true)  {
            &mut (x)
        } else {
            &mut (copy x)
        } != &mut (*(copy y));
    }
}
```

Compiling with V1 will cause:
```
bug: BYTECODE VERIFICATION FAILED
  ┌─ ~/debug_package/sources/repro.move:7:11
  │
7 │         } != &mut (*(copy y));
  │           ^^ ICE failed bytecode verifier: VMError {
    major_status: EQUALITY_OP_TYPE_MISMATCH_ERROR,
```

**Comment by zzjas** [comment]
# 🐛 Bug

```
module 0xCAFE::Module0 {
    struct S has copy, drop, store, key {}
    public fun f() acquires S {
        if (true)  { } else { borrow_global_mut<S>(@0xBEEF); };
    }
}
```

Compiling with V1 will cause:
```
bug: BYTECODE VERIFICATION FAILED
  ┌─ ~/debug_package/sources/repro.move:1:16
  │
1 │ module 0xCAFE::Module0 {
  │                ^^^^^^^ ICE failed bytecode verifier: VMError {
    major_status: EXTRANEOUS_ACQUIRES_ANNOTATION,
```

**Comment by zzjas** [comment]
# 🐛 Bug

```
module 0xCAFE::Module0 {
    public fun f(x: bool) {
        let y = &x;
        y = copy y;
        x = true;
        copy x;
    }
}
```

Compiling with V1 will cause:
```
error[E07003]: invalid operation, could create dangling a reference
  ┌─ ~/debug_package/sources/repro.move:5:9
  │
3 │         let y = &x;
  │                 -- It is still being borrowed by this reference
4 │         y = copy y;
5 │         x = true;
  │         ^ Invalid assignment of variable 'x'
```

V2 compiles fine.

**Comment by zzjas** [comment]
```move
module 0xCAFE::Module0 {
    const ADDR: address = @0xBEEF;

    struct S has copy, drop, store, key {}

    public fun f1() acquires S {
        let x = borrow_global<S>(ADDR);
        f2<S>(
            if (true) {
                *(copy x)
            } else {
                S {}
            }
        );
    }

    public fun f2<T: copy + drop + store>(_: T) acquires S {
        borrow_global_mut<S>(ADDR);
    }
}
```


This compiles fine with V2, but V1 will fail bytecode verifier:
```
bug: BYTECODE VERIFICATION FAILED
   ┌─ ~/debug_package/sources/repro.move:9:9
   │  
 9 │ ╭         f2<S>(
10 │ │             if (true) {
11 │ │                 *(copy x)
12 │ │             } else {
13 │ │                 S {}
14 │ │             },
15 │ │         );
   │ ╰─────────^ ICE failed bytecode verifier: VMError {
    major_status: GLOBAL_REFERENCE_ERROR,
```

It's interesting that it cannot be minimized it further. Cannot remove the function call or the if-else.

**Comment by zzjas** [comment]
V1 bug that fails bytecode verifier with `READREF_EXISTS_MUTABLE_BORROW_ERROR`:
```
//# publish
module 0xCAFE::Module0 {
    public fun function0(): bool {
        let x: u16 = 0;

        if (false) { &mut (0) } else { &mut (x) }
        !=
        if (true) { &mut (x) } else { &mut (0) }
    }
}
```

Compiling with V1 gives:
```
bug: BYTECODE VERIFICATION FAILED
  ┌─ ~/debug_package/sources/MoveSmith.move:7:9
  │
7 │         !=
  │         ^^ ICE failed bytecode verifier: VMError {
    major_status: READREF_EXISTS_MUTABLE_BORROW_ERROR,
```
V2 can compile fine.

**Comment by zzjas** [comment]
```move
module 0xCAFE::Module0 {
    use 0x1::vector;
    struct S has copy, drop {}

    public fun f() {
        let v: vector<S> = vector::empty<S>();
        let e: &S = vector::borrow<S>(&v, 0);
        vector::push_back<S>(&mut v, *(copy e));
    }
}
```

V2 can compile this. V1 will fail with:
```
error[E07005]: invalid transfer of references
  ┌─ ~/debug_package/sources/MoveSmith.move:9:9
  │
8 │         let e: &S = vector::borrow<S>(&v, 0);
  │                     ------------------------ It is still being borrowed by this reference
9 │         vector::push_back<S>(&mut v, *(copy e));
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid usage of reference as function argument. Cannot transfer a mutable reference that is being borrowed
```

**Comment by vineethk** [comment]
Closing as not planned to do.
