### ISSUE TITLE
[Bug] Aptos CLI install cli script broken on Linux & Github release page got wrong version

### ISSUE THREAD

**Issue by alex4506** [aptos-labs/aptos-core#15056]
# 🐛 Bug 1

`curl -fsSL "https://aptos.dev/scripts/install_cli.py" | python3`

Got

```
Latest CLI release: 4.2.4
Currently installed CLI: None
Installing 4.2.4
Determined target to be: Ubuntu-22.04-x86_64

Welcome to the Aptos CLI installer!

This will download and install the latest version of the Aptos CLI at this location:

/root/.local/bin

Installing Aptos CLI (4.2.4): Downloading...
Traceback (most recent call last):
  File "<stdin>", line 571, in <module>
  File "<stdin>", line 550, in main
  File "<stdin>", line 281, in run
  File "<stdin>", line 301, in install
  File "/usr/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

# 🐛 Bug 2

The latest release version in `https://github.com/aptos-labs/aptos-core/releases?q=cli&expanded=true` should be `4.2.4`, but the package in `Assets` is `4.2.3`

**Comment by banool** [comment]
We released a new version of the CLI with the correct tagging, this should be fixed now.
