### ISSUE TITLE
[Bug] In Your First NFT , the typescript example transfer token failed

### ISSUE THREAD

**Issue by passer-byzhang** [aptos-labs/aptos-core#2381]
# 🐛 Bug

In Your First NFT  tutorial, the typescript example transfer token failed.It seems like can't find "tokenTransfers"

## To reproduce
change directories to developer-docs-site/static/examples/typescript
run `npm install`
and run `ts-node first_nft.ts`
**Code snippet to reproduce**
```
async claimToken(account: Account, sender: string, creator: string, collection_name: string, token_name: string) {
    const payload: { function: string; arguments: string[]; type: string; type_arguments: any[] } = {
      type: "script_function_payload",
      function: "0x1::tokenTransfers::claim_script",
      type_arguments: [],
      arguments: [
        sender,
        creator,
        Buffer.from(collection_name).toString("hex"),
        Buffer.from(token_name).toString("hex"),
      ],
    };
    await this.submitTransactionHelper(account, payload);
  }
```

**Stack trace/error message**
```
=== Addresses ===
Alice: 8466adfb14f2247ce5bd472ca3535e50c8deef115b6c49124bbf038161072687. Key Seed: d84192cdb47b51e6fdfdb0dff6588f6ae7623d7fd43301c8d6182e80b3a40dbd
Bob: d335e871542efd78870035a01d2080de5c6c950254d56946592466c8920972dd. Key Seed: 48fa535cdb4a4295b1955915b124c71df1b06f873d8a8e0b1254fe8b74cc038d

=== Initial Balances ===
Alice: 20000
Bob: 20000

=== Creating Collection and Token ===
Alice's token balance: 1
Alice's token data: {"collection":"Alice's","description":"Alice's simple token","maximum":{"vec":[]},"name":"Alice's first token","royalty":{"creator_account":"0x8466adfb14f2247ce5bd472ca3535e50c8deef115b6c49124bbf038161072687","royalty_points_per_million":"0"},"supply":{"vec":["1"]},"uri":"https://aptos.dev/img/nyan.jpeg"}

=== Transferring the token to Bob ===
/Users/idok/aptos/aptos-core/developer-docs-site/static/examples/typescript/first_transaction.ts:109
      assert(response.status == 200, (await response.text()) + " - " + JSON.stringify(txnRequest));
            ^
AssertionError [ERR_ASSERTION]: {"code":400,"message":"invalid request body: invalid UserTransactionRequest: Module ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000001, name: Identifier(\"tokenTransfers\") } can't be found"} - {"sender":"0x8466adfb14f2247ce5bd472ca3535e50c8deef115b6c49124bbf038161072687","sequence_number":"2","max_gas_amount":"2000","gas_unit_price":"1","expiration_timestamp_secs":"1659238455","payload":{"type":"script_function_payload","function":"0x1::tokenTransfers::offer_script","type_arguments":[],"arguments":["d335e871542efd78870035a01d2080de5c6c950254d56946592466c8920972dd","8466adfb14f2247ce5bd472ca3535e50c8deef115b6c49124bbf038161072687","416c6963652773","416c696365277320666972737420746f6b656e","1"]}}
    at RestClient.signTransaction (/Users/idok/aptos/aptos-core/developer-docs-site/static/examples/typescript/first_transaction.ts:109:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TokenClient.submitTransactionHelper (/Users/idok/aptos/aptos-core/developer-docs-site/static/examples/typescript/first_nft.ts:18:24)
    at async TokenClient.offerToken (/Users/idok/aptos/aptos-core/developer-docs-site/static/examples/typescript/first_nft.ts:88:5)
    at async main (/Users/idok/aptos/aptos-core/developer-docs-site/static/examples/typescript/first_nft.ts:218:3) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

```

## System information

**Please complete the following information:**
- 
- 
- 
Node Version:16.15.1
Aptos Core Version:https://github.com/aptos-labs/aptos-core/commit/225956224def77f67547b34685f40611679274d9
Computer OS: macOS 11.4

**Comment by passer-byzhang** [comment]
"0x1::tokenTransfers::claim_script" should be ""0x1::token_transfers::claim_script","

**Comment by passer-byzhang** [comment]
"0x1::tokenTransfers::claim_script" should be ""0x1::token_transfers::claim_script", I commit  a PR in https://github.com/aptos-labs/aptos-core/pull/2382

**Comment by davidiw** [comment]
Thanks!
