### ISSUE TITLE
[Bug] While achieving sync: [state-sync-driver] ERROR crates/crash-handler/src/lib.rs:39 details panicked at 'assertion failed...

### ISSUE THREAD

**Issue by sirouk** [aptos-labs/aptos-core#2473]
# 🐛 Bug

The aptos-node binary is panicked and crashing and the output buffer prints this ERROR:

2022-08-03T02:35:02.336977Z [state-sync-driver] ERROR crates/crash-handler/src/lib.rs:39 details = '''panicked at 'assertion failed: self.base_smt.is_the_same(&since_smt.base_smt)', /home/maskeduser/aptos-core/storage/scratchpad/src/sparse_merkle/mod.rs:483:9'''

The full backtrace is in the attached log file.

NOTE: It is possible to simply restart the node, and it will continue to make progress syncing. This issue may happen a few times before reaching full sync. This issue does not appear to happen at all once fully synced.

## To reproduce
# Wipe the database
rm -Rf $HOME/aptos-core/config/data
# Sync as a fullnode with or without piping to a log
aptos-node -f ~/$WORKSPACE/fullnode.yaml

**Stack trace/error message**
```
   0:     0x5576859d0697 - backtrace::backtrace::libunwind::trace::hc3d3981a04b54342
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::hefd8b699e1a18ebd
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h88137f36a81cc10a
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/backtrace/mod.rs:53:14
   1:     0x5576859bd735 - backtrace::capture::Backtrace::create::ha7f21f6625997d1b
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h189a8188524474e8
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.65/src/capture.rs:140:22
   2:     0x5576846d91ba - crash_handler::handle_panic::h5e98920e340e601b
                               at /home/maskeduser/aptos-core/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::h88bfe09c70ed0c96
                               at /home/maskeduser/aptos-core/crates/crash-handler/src/lib.rs:27:9
   3:     0x557685ee56e0 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   4:     0x557685ee54d9 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:586:13
   5:     0x557685ee3a54 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   6:     0x557685ee5249 - rust_begin_unwind
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   7:     0x5576840d2e93 - core::panicking::panic_fmt::h366d3a309ae17c94
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   8:     0x5576840d2d5d - core::panicking::panic::h8705e81f284be8a5
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   9:     0x557684c37994 - scratchpad::sparse_merkle::FrozenSparseMerkleTree<V>::new_node_hashes_since::h45c3a278058aa569
                               at /home/maskeduser/aptos-core/storage/scratchpad/src/sparse_merkle/mod.rs:483:9
  10:     0x557684c8a1a3 - <aptosdb::AptosDB as storage_interface::DbWriter>::save_state_snapshot::{{closure}}::h15ed852201534d6a
                               at /home/maskeduser/aptos-core/storage/aptosdb/src/lib.rs:1354:31
                           aptosdb::gauged_api::h0540f69d315da664
                               at /home/maskeduser/aptos-core/storage/aptosdb/src/lib.rs:1685:15
                           <aptosdb::AptosDB as storage_interface::DbWriter>::save_state_snapshot::h1a48c7d97dc0e30b
                               at /home/maskeduser/aptos-core/storage/aptosdb/src/lib.rs:1352:9
  11:     0x557684c8c356 - <aptosdb::AptosDB as storage_interface::DbWriter>::save_transactions_ext::{{closure}}::h34b7006ecd4fe230
                               at /home/maskeduser/aptos-core/storage/aptosdb/src/lib.rs:1493:21
                           aptosdb::gauged_api::hc0c85925f5c82a82
                               at /home/maskeduser/aptos-core/storage/aptosdb/src/lib.rs:1685:15
                           <aptosdb::AptosDB as storage_interface::DbWriter>::save_transactions_ext::h15da96fd53862b69
                               at /home/maskeduser/aptos-core/storage/aptosdb/src/lib.rs:1394:9
  12:     0x5576841fdea6 - storage_interface::DbWriter::save_transactions::hcd24dc89f681c82e
                               at /home/maskeduser/aptos-core/storage/storage-interface/src/lib.rs:644:9
  13:     0x557684381d43 - executor::chunk_executor::ChunkExecutorInner<V>::commit_chunk_impl::h5db331ab4a74ff17
                               at /home/maskeduser/aptos-core/execution/executor/src/chunk_executor.rs:192:13
                           executor::chunk_executor::ChunkExecutorInner<V>::commit_chunk::h2c55172f1a13b21a
                               at /home/maskeduser/aptos-core/execution/executor/src/chunk_executor.rs:316:30
  14:     0x557684365f30 - <executor::chunk_executor::ChunkExecutor<V> as executor_types::ChunkExecutorTrait>::commit_chunk::h7acf747b46aac4a2
                               at /home/maskeduser/aptos-core/execution/executor/src/chunk_executor.rs:89:9
  15:     0x5576841b9416 - state_sync_driver::storage_synchronizer::spawn_committer::{{closure}}::h71d2b11da1b6dbd4
                               at /home/maskeduser/aptos-core/state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs:453:27
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h156ff163842ec957
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  16:     0x55768428a507 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::hcc280684348abf46
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h14048519ae1039d1
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
                           tokio::runtime::task::core::CoreStage<T>::poll::h16fbdedf3cb860d6
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  17:     0x55768435821d - tokio::runtime::task::harness::poll_future::{{closure}}::h85820ebe44c52266
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7c35efed54ca53ed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
                           std::panicking::try::do_call::hdde11bf5af6d2a09
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
                           std::panicking::try::h0a416d4ce873264a
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::h789a01e5da29e4bf
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
                           tokio::runtime::task::harness::poll_future::h65f85e9500aa88a7
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  18:     0x55768435ad0e - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h96f9d5ea96aa559c
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
                           tokio::runtime::task::harness::Harness<T,S>::poll::h4ce84306020f3bbe
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  19:     0x557685c35735 - tokio::runtime::task::raw::RawTask::poll::h257421a6efb40fc6
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
                           tokio::runtime::task::LocalNotified<S>::run::haec9cce106be1f8e
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:376:9
                           tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::h66f9dedda99efb0b
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:431:13
                           tokio::coop::with_budget::{{closure}}::ha55b172a690e14ea
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
                           std::thread::local::LocalKey<T>::try_with::h5715071a2f799c63
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
                           std::thread::local::LocalKey<T>::with::h94e97794640fc0ef
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  20:     0x557685c50e41 - tokio::coop::with_budget::he97241c0a7a27367
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
                           tokio::coop::budget::h9124b104aa3f0e12
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
                           tokio::runtime::thread_pool::worker::Context::run_task::h6622441d1917f723
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:430:9
  21:     0x557685c50210 - tokio::runtime::thread_pool::worker::Context::run::hdd7364b0e6faf42f
  22:     0x557685c3a427 - tokio::runtime::thread_pool::worker::run::{{closure}}::h3f3dfbdbad2fa871
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:382:17
                           tokio::macros::scoped_tls::ScopedKey<T>::set::he7ba536353369f71
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  23:     0x557685c4fd7b - tokio::runtime::thread_pool::worker::run::hc49af12f56421e95
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:379:5
  24:     0x557685c31871 - tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}::h8d53cd16034ace6b
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:358:45
                           <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h5c5c9f9417776a2b
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/task.rs:42:21
  25:     0x557685c47be9 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h79acf9bbd9054749
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hd35a2180a57fa111
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
                           tokio::runtime::task::core::CoreStage<T>::poll::h2cc5432708ea8759
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
                           tokio::runtime::task::harness::poll_future::{{closure}}::hd4fc4b01a8d2659f
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9a46a88cad7980c5
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
                           std::panicking::try::do_call::h9df2472ff085ae1d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
                           std::panicking::try::hdcbcdb8c6fca0d40
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::h3037d31380d919e7
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
                           tokio::runtime::task::harness::poll_future::h174aa26cefc3f0e5
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
                           tokio::runtime::task::harness::Harness<T,S>::poll_inner::h600588e5eace4a79
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
                           tokio::runtime::task::harness::Harness<T,S>::poll::h31dba841fc2466ba
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  26:     0x557685c45aa5 - tokio::runtime::task::raw::RawTask::poll::h257421a6efb40fc6
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
                           tokio::runtime::task::UnownedTask<S>::run::h6f27c4ca7a57c3bb
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:413:9
                           tokio::runtime::blocking::pool::Task::run::h10dd86b80ee90bb8
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:91:9
                           tokio::runtime::blocking::pool::Inner::run::hb71f176ebb48dc23
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:325:17
  27:     0x557685c37d31 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h7a6c8028e59ad886
                               at /home/maskeduser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:300:13
                           std::sys_common::backtrace::__rust_begin_short_backtrace::h365c2eef76f6cee2
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
  28:     0x557685c3cb1f - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::ha394b29647a276d7
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/mod.rs:498:17
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hdca5925a45e0db89
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
                           std::panicking::try::do_call::h0104286b6386ae53
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
                           std::panicking::try::hf8ce95a8323ad0f1
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::h36d1bfff754fb636
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
                           std::thread::Builder::spawn_unchecked_::{{closure}}::h9c40662bef38f1d9
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/mod.rs:497:30
                           core::ops::function::FnOnce::call_once{{vtable.shim}}::h970dc012c57524a0
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  29:     0x557685ee9273 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha99802c2c52ada61
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha39aea1c57e28a15
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
                           std::sys::unix::thread::Thread::new::thread_start::h9f8e3d72b1f7662f
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
  30:     0x7f514f072609 - start_thread
  31:     0x7f514e8da133 - clone
  32:                0x0 - <unknown>
```

## Expected Behavior
I would expect the node to sync and errors to be caught without making the binary dump and require a restart of the binary.

## System information

- Aptos Node 0.1.0
- cargo 1.62.1 (a748cf5a3 2022-06-08)
- Ubuntu 20.04.4 LTS

## Additional context
[aptos-node_panicked_while_syncing_2022-08-02.txt](https://github.com/aptos-labs/aptos-core/files/9247497/aptos-node_panicked_while_syncing_2022-08-02.txt)

**Comment by sirouk** [comment]
## Here is the issue reproduced with logger.level set to DEBUG!

# Wipe the database
rm -Rf $HOME/aptos-core/config/data

# Sync as a fullnode with or without piping to a log
aptos-node -f ~/$WORKSPACE/fullnode.yaml


[aptos-node_panicked_while_syncing_2022-08-02_w-DEBUG.txt](https://github.com/aptos-labs/aptos-core/files/9247685/aptos-node_panicked_while_syncing_2022-08-02_w-DEBUG.txt)

**Comment by lightmark** [comment]
PR https://github.com/aptos-labs/aptos-core/pull/2495 will fix this.

**Comment by gregnazario** [comment]
@lightmark looks like you've pushed the fix for this so I'll close it.  Thanks for reporting this!

**Comment by sirouk** [comment]
Awesome, thanks!
