### ISSUE TITLE
[Bug] indexer panic - number too large to fit in target type

### ISSUE THREAD

**Issue by topazso** [aptos-labs/aptos-core#2555]
# 🐛 Bug

Indexer is panicking, perhaps there should be some validation on the token creation side to not allow token data that will panic the indexer or some behavior that skips token data that is invalid.

## To reproduce
Running the docker indexer with `--index-token-data` flag.
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("number too large to fit in target type", line: 0, column: 0)', ecosystem/indexer/src/models/token.rs:154:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
{"level":"ERROR","source":{"package":"aptos_indexer","file":"ecosystem/indexer/src/indexer/tailer.rs:272"},"thread_name":"tokio-runtime-worker","hostname":"aptos-indexer.local","timestamp":"2022-08-05T03:30:54.771165Z","message":"Error joining task: Err(JoinError::Panic(Id(5041), ...))"}
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(5041), ...)', /aptos/ecosystem/indexer/src/indexer/tailer.rs:274:29
{"level":"ERROR","source":{"package":"aptos_indexer","file":"ecosystem/indexer/src/indexer/tailer.rs:272"},"thread_name":"main","hostname":"aptos-indexer.local","timestamp":"2022-08-05T03:30:54.771330Z","message":"Error joining task: Err(JoinError::Panic(Id(4827), ...))"}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(4827), ...)', /aptos/ecosystem/indexer/src/indexer/tailer.rs:274:29
```

## Additional context

This is what's causing the error. https://github.com/aptos-labs/aptos-core/blob/devnet/ecosystem/indexer/src/models/token.rs#L154

Possibly related to bug(?) in the SDK which still hex encodes data?

https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/token_client.ts#L60

**Comment by topazso** [comment]
Could this be what's breaking the indexer? Like this number is too big for serde? `9007199254740991`

https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/token_client.ts#L9

**Comment by topazso** [comment]
https://github.com/aptos-labs/aptos-core/issues/2579
