### ISSUE TITLE
[Bug][Move Prover] Panicked during `translate_write_back_update`

### ISSUE THREAD

**Issue by junkil-park** [aptos-labs/aptos-core#2581]
# 🐛 Bug

Panicked during `translate_write_back_update`

## To reproduce
**Code snippet to reproduce & Stack trace/error message**

To reproduce, one need merge these first to rule out the other issues:
https://github.com/move-language/move/pull/347
https://github.com/aptos-labs/aptos-core/pull/2441

and then, run Prover with `-t big_vector.move` in `aptos-core/aptos-move/framework/aptos-stdlib`
```
[INFO] preparing module 0x1::big_vector
[INFO] transforming bytecode
[INFO] generating verification conditions
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', language/move-model/src/ty.rs:290:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:84:5
   3: move_model::ty::Type::replace
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: move_model::ty::Type::replace
   6: move_prover_boogie_backend::bytecode_translator::FunctionTranslator::translate_write_back_update
   7: move_prover_boogie_backend::bytecode_translator::FunctionTranslator::translate_write_back
   8: move_prover_boogie_backend::bytecode_translator::FunctionTranslator::translate_bytecode
   9: move_prover_boogie_backend::bytecode_translator::FunctionTranslator::translate
  10: move_prover_boogie_backend::bytecode_translator::BoogieTranslator::translate
  11: move_prover::generate_boogie
  12: move_prover::run_move_prover_with_model
  13: move_cli::base::prove::run_move_prover
  14: move_cli::base::prove::Prove::execute
  15: move_cli::run_cli
  16: move_cli::move_cli
  17: move::main
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
```

## Expected Behavior

Prover finishes without any error.

**Comment by junkil-park** [comment]
I let Meng know about this issue, and believe that he will look at this issue (@wrwg).
