### ISSUE TITLE
[Bug] Subsequent `aptos node run-local-testnet` crashes with address in use

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#2622]
# 🐛 Bug

Title says it

## To reproduce

```rust
aptos node run-local-testnet
aptos node run-local-testnet
```

**Stack trace/error message**
```
'panicked at 'error binding to 0.0.0.0:9101: error creating server listener: Address already in use (os error 48)', /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/server/server.rs:77:13'''
backtrace = '''
   0:        0x10479e4b0 - backtrace::backtrace::libunwind::trace::h518e78ab4948784e
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h0b7ac7c54f9fd496
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h38bf5c9c1c766b05
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
                           backtrace::capture::Backtrace::create::h43ddd1ccfc356059
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
   1:        0x10479e414 - backtrace::capture::Backtrace::new::h323c1d0871949186
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:        0x103212f40 - crash_handler::handle_panic::hadc2d5edf6a0f27c
                               at /Users/wrwg/aptos-core/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::h0be4238982f89b74
                               at /Users/wrwg/aptos-core/crates/crash-handler/src/lib.rs:27:9
   3:        0x105509e64 - std::panicking::rust_panic_with_hook::hd083a3aa5c934ce6
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:702:17
   4:        0x105509cbc - std::panicking::begin_panic_handler::{{closure}}::hb5be8aaa10a229ca
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
   5:        0x10550838c - std::sys_common::backtrace::__rust_end_short_backtrace::h68e10e4f00198298
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
   6:        0x105509a14 - rust_begin_unwind
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   7:        0x10561e194 - core::panicking::panic_fmt::hffc63a015c61fdde
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   8:        0x104836420 - hyper::server::server::Server<hyper::server::tcp::AddrIncoming,()>::bind::{{closure}}::h29a9593ea9b81bdb
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/server/server.rs:77:13
                           core::result::Result<T,E>::unwrap_or_else::hd814c22ba13bb9fa
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1464:23
                           hyper::server::server::Server<hyper::server::tcp::AddrIncoming,()>::bind::h606d6cbfc7f9492f
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.20/src/server/server.rs:76:24
   9:        0x103211e44 - inspection_service::inspection_service::start_inspection_service::{{closure}}::{{closure}}::h3f9f9f5a5f8cfdd2
                               at /Users/wrwg/aptos-core/crates/inspection-service/src/inspection_service.rs:173:30
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4ae7062e706cce8e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  10:        0x103191a9c - <core::pin::Pin<P> as core::future::future::Future>::poll::h9f7d51ebbfbceba3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
                           tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}::h3a90c417a023c3b2
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:543:48
                           tokio::coop::with_budget::{{closure}}::h2b018b812065f3b5
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
                           std::thread::local::LocalKey<T>::try_with::hfdd1fd009525f7f7
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:445:16
                           std::thread::local::LocalKey<T>::with::h144fc356524067b3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:421:9
  11:        0x1032116f8 - tokio::coop::with_budget::h9e65acbe1727b60a
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
                           tokio::coop::budget::hee8065c69dda9f21
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
                           tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::hb64c7fa79ebb978a
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:543:25
                           tokio::runtime::basic_scheduler::Context::enter::h557fe4e54f45ea6b
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:367:19
  12:        0x103206b54 - tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::h9c5480de7da5dd57
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:542:36
                           tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}::h009368b926ee3b79
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:613:57
                           tokio::macros::scoped_tls::ScopedKey<T>::set::h33443727ef83ca04
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/scoped_tls.rs:61:9
  13:        0x1032113e4 - tokio::runtime::basic_scheduler::CoreGuard::enter::hb676113cc8e8ae56
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:613:27
                           tokio::runtime::basic_scheduler::CoreGuard::block_on::h6d0122e67e263000
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:533:19
                           tokio::runtime::basic_scheduler::BasicScheduler::block_on::h732699fa9ea93c39
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/basic_scheduler.rs:179:24
  14:        0x1031e84b0 - tokio::runtime::Runtime::block_on::h225bb204e79727e1
                               at /Users/wrwg/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/mod.rs:482:46
  15:        0x103191908 - inspection_service::inspection_service::start_inspection_service::{{closure}}::h8894f05530038bb7
                               at /Users/wrwg/aptos-core/crates/inspection-service/src/inspection_service.rs:171:9
                           std::sys_common::backtrace::__rust_begin_short_backtrace::hbb570ebb6c5aacd1
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
  16:        0x1031d301c - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h1e710840ed33f6d2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/mod.rs:501:17
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h5be0823d1c8e1252
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panic/unwind_safe.rs:271:9
                           std::panicking::try::do_call::h906f96c16f04d640
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
                           std::panicking::try::hfc26cd2e095c130c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::h75bbadb5032dd58d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
                           std::thread::Builder::spawn_unchecked_::{{closure}}::h705212cbdb05f89e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/mod.rs:500:30
                           core::ops::function::FnOnce::call_once{{vtable.shim}}::hf334e7aa28b54a6f
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  17:        0x10550e9f0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h09b61491814d7224
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3d30a2aa82370bb4
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/boxed.rs:1872:9
                           std::sys::unix::thread::Thread::new::thread_start::hacb0bdc43acdb831
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys/unix/thread.rs:108:17

```

## Expected Behavior

Better error message

## System information

Current head
MacOs

**Comment by gregnazario** [comment]
Yes, it's not built to have 2 local testnets run at the same time.  I guess we could parse the entire config and check if all of the ports conflict, but it seems like low priority

**Comment by wrwg** [comment]
Stack trace indicates internal error for me. If it just say the core error message I wouldn't mind.

BTW, I get the same message with `aptos node run-local-testnet --force-restart` ...

**Comment by gregnazario** [comment]
Yes,there's no global lock or anything on the CLI process running the node.  Internal error could be better than that, just it'll take a while
