### ISSUE TITLE
[Bug] typescript examples cannot compile because of stale reference to getAccountResource

### ISSUE THREAD

**Issue by li-dennis** [aptos-labs/aptos-core#2688]
# 🐛 Bug

`getAccountResource` expects a `resourceType` in the form of `MoveStructTag`, but a string is supplied instead in the examples.

aptos_client.ts
```
  async getAccountResource(
    accountAddress: MaybeHexString,
    resourceType: Gen.MoveStructTag,
    query?: { ledgerVersion?: BigInt },
  )
```

hello_blockchain.ts
```
    const resource = await client.getAccountResource(
      accountAddress,
      `${contractAddress.toString()}::message::MessageHolder`,
    );
```

first_transaction.ts
```
  const resource = await client.getAccountResource(accountAddress, "0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>");
```

## Steps to reproduce

```
cd developer-docs-site/static/examples/typescript
yarn
yarn hello_blockchain Message.mv
```

produces the following error:
```
❯ yarn hello_blockchain Message.mv

yarn run v1.22.19
$ node --loader ts-node/esm hello_blockchain.ts Message.mv
(node:26379) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
.../aptos-core/developer-docs-site/static/examples/typescript/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
hello_blockchain.ts:51:7 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'MoveStructTag'.

51       `${contractAddress.toString()}::message::MessageHolder`,
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

** Error message or problem **
See Above

## Expected Behavior

```
❯ yarn hello_blockchain Message.mv

yarn run v1.22.19
$ node --loader ts-node/esm hello_blockchain.ts Message.mv
(node:26586) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

=== Addresses ===
Alice: 0xfc3999c13224ef9bcb90a9c5f5a99663024264d316aaac31bc5b3644139ac457
Bob: 0xd84f3f87e4c3d956af988e32bf1d63fecc18be689018db223c9144bdec7b8fb2
.../crypto/aptos-core/developer-docs-site/static/examples/typescript/node_modules/aptos/src/aptos_client.ts:417
        throw new Error(`Waiting for transaction ${txnHash} timed out!`);
              ^
Error: Waiting for transaction 017fa89d1ab0cc986db7cca6f1d86d6270cf2c9fe6a1548c846e55e1d6dff7cf timed out!
    at FaucetClient.waitForTransaction...
```

(I'm not sure if timing out is expected here, as I may be doing something wrong)
## System information
OSX 12.5

## Additional context
Diff fixing the example code is below
```
❯ git diff
diff --git a/developer-docs-site/static/examples/typescript/first_transaction.ts b/developer-docs-site/static/examples/typescript/first_transaction.ts
index 498fd17df2..eaab4ec0d4 100644
--- a/developer-docs-site/static/examples/typescript/first_transaction.ts
+++ b/developer-docs-site/static/examples/typescript/first_transaction.ts
@@ -43,7 +43,15 @@ const client = new AptosClient(NODE_URL);
 //:!:>section_5
 /** Helper method returns the coin balance associated with the account */
 export async function accountBalance(accountAddress: MaybeHexString): Promise<number | null> {
-  const resource = await client.getAccountResource(accountAddress, "0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>");
+  const resource = await client.getAccountResource(
+    accountAddress,
+    {
+      address: '0x1',
+      module: 'coin',
+      name: 'CoinStore',
+      generic_type_params: ['0x1::aptos_coin::AptosCoin']
+    }
+  );
   if (resource == null) {
     return null;
   }
diff --git a/developer-docs-site/static/examples/typescript/hello_blockchain.ts b/developer-docs-site/static/examples/typescript/hello_blockchain.ts
index 6799a14168..46dceab25d 100644
--- a/developer-docs-site/static/examples/typescript/hello_blockchain.ts
+++ b/developer-docs-site/static/examples/typescript/hello_blockchain.ts
@@ -48,7 +48,12 @@ async function getMessage(contractAddress: HexString, accountAddress: MaybeHexSt
   try {
     const resource = await client.getAccountResource(
       accountAddress,
-      `${contractAddress.toString()}::message::MessageHolder`,
+      {
+        address: contractAddress.toString(),
+        module: 'message',
+        name: 'MessageHolder',
+        generic_type_params: []
+      }
     );
     return (resource as any).data["message"];
   } catch (_) {
```

**Comment by graysonsun** [comment]
Same issue
-----
yarn run v1.22.19
$ node --loader ts-node/esm first_transaction.ts
(node:96551) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/grayson/development/aptos-core/developer-docs-site/static/examples/typescript/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
first_transaction.ts:46:68 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'MoveStructTag'.

46   const resource = await client.getAccountResource(accountAddress, "0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>");
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/grayson/development/aptos-core/developer-docs-site/static/examples/typescript/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/grayson/development/aptos-core/developer-docs-site/static/examples/typescript/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/grayson/development/aptos-core/developer-docs-site/static/examples/typescript/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/grayson/development/aptos-core/developer-docs-site/static/examples/typescript/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/grayson/development/aptos-core/developer-docs-site/static/examples/typescript/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/grayson/development/aptos-core/developer-docs-site/static/examples/typescript/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29) {
  diagnosticCodes: [ 2345 ]
}

**Comment by jjleng** [comment]
`rm -rf node_modules && yarn && yarn first_transaction`

**Comment by jjleng** [comment]
The issue is caused by a breaking change in SDK. We have downgraded the SDK version in the examples. You need to remove "node_modules" and rerun the examples.

**Comment by weizier** [comment]
I have the same issue,  do I need to change the string-like resourceType to a struct or just pull the newest devnet branch from this repository?

**Comment by jjleng** [comment]
Make sure you are in folder `aptos-core/developer-docs-site/static/examples/typescript`, and run `rm -rf node_modules; yarn && yarn first_transaction`. The compatible SDK version with the examples is 1.2.2.  A new version of SDK that is backward compatible is going to be released soon.

**Comment by weizier** [comment]
Thanks, but if you are not on the main branch, make sure the Aptos SDK version in package.json is 1.2.2.
