### ISSUE TITLE
[Bug] cached-framework-packages build-script errormapgen

### ISSUE THREAD

**Issue by alinush** [aptos-labs/aptos-core#2762]
# 🐛 Bug

`cargo build` fails in the main repo after adding a new Move module in `aptos-move/framework/aptos-stdlib/sources/` and modifying the `bit_vector` module in `aptos-move/framework/move-stdlib/sources/`

## To reproduce

Check out [this commit](https://github.com/aptos-labs/aptos-core/pull/2671/commits/77ee28ddd9343bccf9fef6037ee93e0588147154) and try to `cargo build`.

**Stack trace/error message**
```
--- stderr
  Warning: failed to extract old module APIs -- path "/Users/alinush/repos/aptos-core/target/debug/build/cached-framework-packages-186edf497f419aa3/out/framework" is not a directory
  Warning: failed to extract old module APIs -- path "/Users/alinush/repos/aptos-core/target/debug/build/cached-framework-packages-186edf497f419aa3/out/token" is not a directory
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid abort code constant [236, 211, 245, 92, 26, 99, 18, 88, 214, 156, 247, 162, 222, 249, 222, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16] found for code ELL_MINUS_ONE', /Users/alinush/.cargo/git/checkouts/move-0639dd674f581c30/76c11e3/language/move-prover/move-errmapgen/src/errmapgen.rs:69:47
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
     2: core::result::unwrap_failed
               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1078:23
     4: move_errmapgen::errmapgen::ErrmapGen::gen
               at /Users/alinush/.cargo/git/checkouts/move-0639dd674f581c30/76c11e3/language/move-prover/move-errmapgen/src/errmapgen.rs:69:17
     5: framework::release::generate_error_map
               at /Users/alinush/repos/aptos-core/aptos-move/framework/src/release.rs:161:5
     6: framework::release::ReleaseOptions::create_release
               at /Users/alinush/repos/aptos-core/aptos-move/framework/src/release.rs:120:13
     7: build_script_build::main
               at ./build.rs:56:5
     8: core::ops::function::FnOnce::call_once
               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```

## Expected Behavior

`cargo build` should have succeeded.

## System information

**Please complete the following information:**
- _?? How do I get this ??_
- rustc 1.62.1 (e092d0b6b 2022-07-16)
- MacOS Monterrey 12.5

### Permanent fix

According to @areshand , the problem stems from the fact that 

 > move has this [...] assumption that any constant starting with a E will be treated as an error code. Your  ELL_MINUS_ONE is unfortunately treated as an error code while it is actually not. 

One annoying fix would be to:

 > The fix I would recommend is use other name not starting with E

The problem is in [errmapgen.rs](https://github.com/move-language/move/blob/b53bb030b556a4e6ac2728d50ec7baaddf0b9a56/language/move-prover/move-errmapgen/src/errmapgen.rs#L106):

```rust
fn build_error_map_for_module(
        &mut self,
        module_id: &ModuleId,
        module: &ModuleEnv<'_>,
    ) -> Result<()> {
        for named_constant in module.get_named_constants() {
            let name = self.name_string(named_constant.get_name());
            if name.starts_with(&self.options.error_prefix) {
                let abort_code = self.get_abort_code(&named_constant)?;
                self.output.add_module_error(
                    module_id.clone(),
                    abort_code,
                    ErrorDescription {
                        code_name: name.to_string(),
                        code_description: named_constant.get_doc().to_string(),
                    },
                )?
            }
        }
        Ok(())
    }
```

### Temporary fix

To fix this error, `build.rs` can be patched as per [this commit](https://github.com/aptos-labs/aptos-core/pull/2671/commits/a055302e840af07f580ab0e0132504427668bc50#diff-0f9b0241392db0ae8328e013b3e55d2f2515cb16e70336594ade141d65623c56)

```diff
diff --git a/aptos-move/framework/cached-packages/build.rs b/aptos-move/framework/cached-packages/build.rs
index b2c2f89ea8..5277c1a3b9 100644
--- a/aptos-move/framework/cached-packages/build.rs
+++ b/aptos-move/framework/cached-packages/build.rs
@@ -16,7 +16,7 @@ fn main() {
         with_diagram: false,
         no_script_builder: false,
         no_script_abis: false,
-        no_errmap: false,
+        no_errmap: true,
         package: PathBuf::from("aptos-framework"),
         output: PathBuf::from(format!(
             "{}/{}",
@@ -45,7 +45,7 @@ fn main() {
         with_diagram: false,
         no_script_builder: false,
         no_script_abis: false,
-        no_errmap: false,
+        no_errmap: true,
         package: PathBuf::from("aptos-token"),
         output: PathBuf::from(format!(
             "{}/{}",
```

**Comment by areshand** [comment]
please set no_errmap to 'false'. we still need to generate error code. Please update your constant to a name not using E at prefix.

**Comment by wrwg** [comment]
Any changes to `build.rs` please land soon as I need to refactor all this logic for our upcoming deadlines.

**Comment by alinush** [comment]
Fixed my E's. No changes made to build.rs!

**Comment by davidiw** [comment]
Closing this out as this is an issue in upstream move not aptos.

**Comment by alinush** [comment]
Should I open an issue there? I mean this "feature" is quite unattractive to say the least...

**Comment by wrwg** [comment]
This bug is assigned please don't close it wo/ checking back, @davidiw

**Comment by wrwg** [comment]
This is BTW simply a bug. The const `EXXXX` approach is fine, it can over-approximate which doesn't hurt any, any entries in the error map stemming from that would then be useless but thats it. It should not CRASH though what is the really (likely relative trivial) bug here.

General guideline about a Move bug assigned to me: doesn't really matter its in Aptos, sure in move is cleaner, but practically no difference, so why bother to close it here and reopen over there?

**Comment by wrwg** [comment]
Closing for now, as the crash should be fixed by our reimplementation of errmap generator.
