### ISSUE TITLE
[Bug]thread 'main' panicked at 'Failed to load node config file! Given file path: "/opt/aptos/etc/validator.yaml"

### ISSUE THREAD

**Issue by noprom** [aptos-labs/aptos-core#3153]
# 🐛 Bug

## To reproduce
Following this guide to setup a validator node: https://aptos.dev/nodes/validator-node/run-validator-node-using-docker
**Code snippet to reproduce**
```
wget https://raw.githubusercontent.com/aptos-labs/aptos-core/main/docker/compose/aptos-node/docker-compose.yaml
wget https://raw.githubusercontent.com/aptos-labs/aptos-core/main/docker/compose/aptos-node/validator.yaml

aptos genesis generate-keys --output-dir ./

aptos genesis set-validator-configuration \
    --keys-dir ./ --local-repository-dir ./ \
    --username jarvis \
    --validator-host MYVALIDATORIP:6180
```

```
cat layout.yaml
```

```
---
root_key: "F22409A93D1CD12D2FC92B5F8EB84CDCD24C348E32B3E7A720F3D2E288E63394"
users:
  - "jarvis"
chain_id: 40
min_stake: 0
max_stake: 100000
min_lockup_duration_secs: 0
max_lockup_duration_secs: 2592000
epoch_duration_secs: 86400
initial_lockup_timestamp: 1656615600
min_price_per_gas_unit: 1
allow_new_validators: true
```

```
wget https://github.com/aptos-labs/aptos-core/releases/download/aptos-framework-v0.2.0/framework.zip
unzip framework.zip

aptos genesis generate-genesis --local-repository-dir ./ --output-dir ./
docker-compose up
```

**Stack trace/error message**
```
thread 'main' panicked at 'Failed to load node config file! Given file path: "/opt/aptos/etc/validator.yaml". Error: BCS("genesis", IntegerOverflowDuringUleb128Decoding)', aptos-node/src/lib.rs:136:17
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: aptos_node::AptosNodeArgs::run::{{closure}}
             at ./aptos/aptos-node/src/lib.rs:136:17
   3: core::result::Result<T,E>::unwrap_or_else
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1464:23
   4: aptos_node::AptosNodeArgs::run
             at ./aptos/aptos-node/src/lib.rs:135:26
   5: aptos_node::main
             at ./aptos/aptos-node/src/main.rs:13:5
   6: core::ops::function::FnOnce::call_once
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Expected Behavior

The validator doesn't start
## System information

**Please complete the following information:**
- Aptos Core Version: docker image: `aptoslabs/validator:testnet`
- Computer OS: `Linux version 5.13.0-21-generic (buildd@lgw01-amd64-052) (gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.37) #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021`

**Comment by NimaQu** [comment]
same issue

**Comment by satochi2017** [comment]
```
validator_1  | thread 'main' panicked at 'Failed to load node config file! Given file path: "/opt/aptos/etc/validator.yaml". Error: BCS("genesis", Custom("invalid value: integer `64`, expected variant index 0 <= i < 1"))', aptos-node/src/lib.rs:136:17
```

same issue after download genesis.blob and waypoint.txt
https://raw.githubusercontent.com/aptos-labs/aptos-core/main/terraform/helm/aptos-node/files/test-data/genesis.blob
https://raw.githubusercontent.com/aptos-labs/aptos-core/main/terraform/helm/aptos-node/files/test-data/waypoint.txt

**Comment by LemonTency** [comment]
same issue with [satochi2017](https://github.com/satochi2017)

**Comment by Metatron92** [comment]
Have same error

```
Running `target/release/aptos-node -f /root/testnet/config/validator.yaml`
thread 'main' panicked at 'Failed to load node config file! Given file path: "/root/testnet/config/validator.yaml". Error: IO("genesis", Os { code: 2, kind: NotFound, message: "No such file or directory" })', aptos-node/src/lib.rs:136:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Miguiz** [comment]
Same issue for me with Docker or Source code deploy

**Comment by Metatron92** [comment]
Found solve for me
I change path to files in /root/testnet/config/validator.yaml
Used source code install.

Example validator.yaml file:

`base:
  role: "validator"
  data_dir: "/opt/aptos/data"
  waypoint:
    from_file: "/root/testnet/waypoint.txt"

consensus:
  safety_rules:
    service:
      type: "local"
    backend:
      type: "on_disk_storage"
      path: /opt/aptos/data/secure-data.json
      namespace: ~
    initial_safety_rules_config:
      from_file:
        waypoint:
          from_file: /root/testnet/waypoint.txt
        identity_blob_path: /root/testnet/keys/validator-identity.yaml
  quorum_store_poll_count: 1

execution:
  genesis_file_location: "/root/testnet/genesis.blob"
  concurrency_level: 4

validator_network:
  discovery_method: "onchain"
  mutual_authentication: true
  identity:
    type: "from_file"
    path: /root/testnet/keys/validator-identity.yaml

full_node_networks:
- network_id:
    private: "vfn"
  listen_address: "/ip4/0.0.0.0/tcp/6181"
  identity:
    type: "from_config"
    **key: ""
    peer_id: ""**

api:
  enabled: true
  address: "0.0.0.0:8080"`
