### ISSUE TITLE
 Column families not opened: stale_node_index[Bug]

### ISSUE THREAD

**Issue by luoxiandong** [aptos-labs/aptos-core#3264]
My machine
aliyun
ubutun20
8core32ram

My Validator Docker instance crash with panicked at 'Node should start correctly: DB failed to open Invalid argument: Column families not opened: stale_node_index
```details = '''
testnet-validator-1  | panicked at 'Node should start correctly: DB failed to open Invalid argument: Column families not opened: stale_node_index
testnet-validator-1  | 
testnet-validator-1  | Stack backtrace:
testnet-validator-1  |    0: aptos_node::setup_environment::{{closure}}
testnet-validator-1  |              at ./aptos/aptos-node/src/lib.rs:487:24
testnet-validator-1  |       core::result::Result<T,E>::map_err
testnet-validator-1  |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:855:27
testnet-validator-1  |       aptos_node::setup_environment
testnet-validator-1  |              at ./aptos/aptos-node/src/lib.rs:478:9
testnet-validator-1  |    1: aptos_node::start
testnet-validator-1  |              at ./aptos/aptos-node/src/lib.rs:194:24
testnet-validator-1  |    2: aptos_node::AptosNodeArgs::run
testnet-validator-1  |              at ./aptos/aptos-node/src/lib.rs:144:13
testnet-validator-1  |    3: aptos_node::main
testnet-validator-1  |              at ./aptos/aptos-node/src/main.rs:13:5
testnet-validator-1  |    4: core::ops::function::FnOnce::call_once
testnet-validator-1  |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
testnet-validator-1  |       std::sys_common::backtrace::__rust_begin_short_backtrace
testnet-validator-1  |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:122:18
testnet-validator-1  |    5: std::rt::lang_start::{{closure}}```
I following the doc to create a Validator node via Docker  (https://aptos.dev/nodes/validator-node/run-validator-node-using-docker/)
Current cli 0.3.1

How to solve it？！！！！

**Comment by msmouse** [comment]
Hi @luoxiandong. Was your disk full at some point? Can you delete the volume and try again?

**Comment by msmouse** [comment]
close due to inactivity
