### ISSUE TITLE
[Bug] TypeScript error in example: Cannot find module 'aptos' or its corresponding type declarations.

### ISSUE THREAD

**Issue by MrToph** [aptos-labs/aptos-core#3466]
# 🐛 Bug

I run the [Your first transaction example](https://aptos.dev/tutorials/your-first-transaction-sdk) and it fails with a TypeScript error:

```typescript
TSError: ⨯ Unable to compile TypeScript:
transfer_coin.ts:9:69 - error TS2307: Cannot find module 'aptos' or its corresponding type declarations.
```

There's an `aptos` package in `node_modules` and it looks okay on first sight. Maybe there's an issue with the local package linking.

## To reproduce

**Code snippet to reproduce**
```bash
git clone git@github.com:aptos-labs/aptos-core.git ~/aptos-core
cd ~/aptos-core/ecosystem/typescript/sdk/examples/typescript
yarn install
yarn run transfer_coin
```

**Stack trace/error message**
```
yarn run v1.22.19
$ ts-node transfer_coin.ts
~/aptos-core/ecosystem/typescript/sdk/examples/typescript/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
transfer_coin.ts:9:69 - error TS2307: Cannot find module 'aptos' or its corresponding type declarations.

9 import { AptosClient, AptosAccount, CoinClient, FaucetClient } from "aptos";
                                                                      ~~~~~~~

    at createTSError (~/aptos-core/ecosystem/typescript/sdk/examples/typescript/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (~/aptos-core/ecosystem/typescript/sdk/examples/typescript/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (~/aptos-core/ecosystem/typescript/sdk/examples/typescript/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (~/aptos-core/ecosystem/typescript/sdk/examples/typescript/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (~/aptos-core/ecosystem/typescript/sdk/examples/typescript/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (~/aptos-core/ecosystem/typescript/sdk/examples/typescript/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  diagnosticCodes: [ 2307 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## System information

**Please complete the following information:**
- aptos commit: 0669d878c1ec3bc946588e97058bbd91f6060576
- `node --version`: v16.15.1
- `yarn --version`: 1.22.19

**Comment by davidiw** [comment]
Looks like the code has been updated since then, can you try again? Re-open if the issue persists.

**Comment by MrToph** [comment]
fixed on latest `main`
