### ISSUE TITLE
[Bug] [INDEXER] Indexer panic - Error("EOF while parsing a value", line: 1, column: 0) 

### ISSUE THREAD

**Issue by snowmetalspirit** [aptos-labs/aptos-core#3504]
# 🐛 Bug

## To reproduce
current aptos-indexer docker devnet tag
`docker compose up -d`

**Stack trace/error message**
```
// Paste the output here
{"level":"INFO","source":{"package":"aptos_indexer","file":"ecosystem/indexer/src/main.rs:126"},"thread_name":"main","hostname":"aptos-indexer.local","timestamp":"2022-08-26T00:14:03.877360Z","message":"Indexer has processed version 170958. Overall average TPS: 1108"}
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: WebClient(reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) })', ecosystem/indexer/src/indexer/fetcher.rs:54:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ecosystem/indexer/src/indexer/fetcher.rs:175:48
```

Last successful processor status was version `170738`

## System information

**Please complete the following information:**
- 
- 
-

**Comment by gregnazario** [comment]
The fix there isn't the only fix, looks like more work will need to be done
