### ISSUE TITLE
Error calling genesis.create_initialize_validators: status ABORTED of type Execution with sub status 65540

### ISSUE THREAD

**Issue by yvvw** [aptos-labs/aptos-core#3537]
Generating Genesis failed with this guide https://aptos.dev/cli-tools/aptos-cli-tool/use-aptos-cli/#generating-genesis. pls help

environment: wsl ubuntu

aptos info
```shell
{
  "Result": {
    "build_branch": "main",
    "build_cargo_version": "cargo 1.62.1 (a748cf5a3 2022-06-08)",
    "build_commit_hash": "e1c6a5713301ed72bf3a846ab9536d002ac801d6",
    "build_os": "linux-x86_64",
    "build_pkg_version": "0.3.1",
    "build_rust_channel": "1.62.1-x86_64-unknown-linux-gnu",
    "build_rust_version": "rustc 1.62.1 (e092d0b6b 2022-07-16)",
    "build_tag": "",
    "build_time": "2022-08-26 18:04:52 +08:00"
  }
}
```

```
```shell
git clone https://github.com/aptos-labs/aptos-core.git
cd aptos-core
git checkout --track origin/testnet
./scripts/dev_setup.sh
source ~/.cargo/env
mkdir genesis
cd genesis
cargo run --package aptos -- genesis generate-layout-template
cargo run --package framework -- release --target testnet
mv testnet.mrb framework.mrb
cargo run --package aptos -- genesis generate-keys --output-dir alices_key
cargo run --package aptos -- genesis generate-keys --output-dir bobs_key
cd alices_key && cargo run --package aptos -- genesis set-validator-configuration --username alice --validator-host alices_host:6180 --full-node-host alices_host:6180 --local-repository-dir . && cd .. && mv alices_key/alice .
cd bobs_key && cargo run --package aptos -- genesis set-validator-configuration --username bob --validator-host bobs_host:6180 --full-node-host bobs_host:6180 --local-repository-dir . && cd .. && mv bobs_key/bob .
# edit layout.yaml add root_key and users
cargo run --package aptos -- genesis generate-genesis --local-repository-dir genesis
```

genesis folder tree view
```
.
├── alice
│   ├── operator.yaml
│   └── owner.yaml
├── alices_key
│   ├── private-keys.yaml
│   ├── public-keys.yaml
│   ├── validator-full-node-identity.yaml
│   └── validator-identity.yaml
├── bob
│   ├── operator.yaml
│   └── owner.yaml
├── bobs_key
│   ├── private-keys.yaml
│   ├── public-keys.yaml
│   ├── validator-full-node-identity.yaml
│   └── validator-identity.yaml
├── framework.mrb
└── layout.yaml
```

run generate-genesis command result
```shell
$ RUST_BACKTRACE=full cargo run --package aptos -- genesis generate-genesis --local-repository-dir .
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `/home/user/projects/aptos-core/target/debug/aptos genesis generate-genesis --local-repository-dir .`
thread 'main' panicked at 'Error calling genesis.create_initialize_validators: status ABORTED of type Execution with sub status 65540', aptos-move/vm-genesis/src/lib.rs:222:13
stack backtrace:
   0:     0x56496a7d9dcd - std::backtrace_rs::backtrace::libunwind::trace::h8e036432725b1c57
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56496a7d9dcd - std::backtrace_rs::backtrace::trace_unsynchronized::h4f83092254c85869
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56496a7d9dcd - std::sys_common::backtrace::_print_fmt::h9728b5e056a3ece3
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x56496a7d9dcd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h48bb4bd2928827d2
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x56496a80351c - core::fmt::write::h909e69a2c24f44cc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
   5:     0x56496a7d1a71 - std::io::Write::write_fmt::h7f4b8ab8af89e9ef
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
   6:     0x56496a7db725 - std::sys_common::backtrace::_print::hff4838ebf14a2171
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x56496a7db725 - std::sys_common::backtrace::print::h2499280374189ad9
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x56496a7db725 - std::panicking::default_hook::{{closure}}::h8b270fc55eeb284e
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
   9:     0x56496a7db399 - std::panicking::default_hook::h3217e229d6e9d13c
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
  10:     0x56496a7dbcf8 - std::panicking::rust_panic_with_hook::h9acb8048b738d2e0
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:698:17
  11:     0x56496a7dbba7 - std::panicking::begin_panic_handler::{{closure}}::h70f3b839526af6dc
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:588:13
  12:     0x56496a7da284 - std::sys_common::backtrace::__rust_end_short_backtrace::h1ecf2cee857fbe0a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x56496a7db8d9 - rust_begin_unwind
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
  14:     0x5649637c7303 - core::panicking::panic_fmt::h9f8393e7fd56d655
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
  15:     0x56496449f4cc - vm_genesis::exec_function::{{closure}}::h417fc6cd15b3ed98
                               at /home/user/projects/aptos-core/aptos-move/vm-genesis/src/lib.rs:222:13
  16:     0x5649644a53d9 - core::result::Result<T,E>::unwrap_or_else::h69f725dba87e88f8
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1464:23
  17:     0x56496449f276 - vm_genesis::exec_function::h7955367f356b8c53
                               at /home/user/projects/aptos-core/aptos-move/vm-genesis/src/lib.rs:210:5
  18:     0x5649644a0c2a - vm_genesis::create_and_initialize_validators::h09eb27e3f3ee792e
                               at /home/user/projects/aptos-core/aptos-move/vm-genesis/src/lib.rs:334:5
  19:     0x5649644a2ad3 - vm_genesis::encode_genesis_change_set::h13939398d757a305
                               at /home/user/projects/aptos-core/aptos-move/vm-genesis/src/lib.rs:123:5
  20:     0x5649644a24e5 - vm_genesis::encode_genesis_transaction::h7d63b3ad3585b9be
                               at /home/user/projects/aptos-core/aptos-move/vm-genesis/src/lib.rs:85:61
  21:     0x56496429f619 - aptos_genesis::GenesisInfo::generate_genesis_txn::h896e32cc6e7bd19f
                               at /home/user/projects/aptos-core/crates/aptos-genesis/src/lib.rs:109:9
  22:     0x56496429f400 - aptos_genesis::GenesisInfo::get_genesis::h58b3bea6c86e3023
                               at /home/user/projects/aptos-core/crates/aptos-genesis/src/lib.rs:103:33
  23:     0x564963a6e44c - <aptos::genesis::GenerateGenesis as aptos::common::types::CliCommand<alloc::vec::Vec<std::path::PathBuf>>>::execute::{{closure}}::h8d66210a553d499c
                               at /home/user/projects/aptos-core/crates/aptos/src/genesis/mod.rs:88:23
  24:     0x5649639c39d2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha78c42b4dbf91f69
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  25:     0x5649637d22fb - <core::pin::Pin<P> as core::future::future::Future>::poll::h66052ac786b2db2a
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  26:     0x5649637f2a1b - aptos::common::types::CliCommand::execute_serialized::{{closure}}::h8dd22afe36ec5c02
                               at /home/user/projects/aptos-core/crates/aptos/src/common/types.rs:880:66
  27:     0x564963831f11 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfa34513030d5fb46
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  28:     0x564965a2ee3f - <core::pin::Pin<P> as core::future::future::Future>::poll::h555a975127cf8a3d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/future.rs:124:9
  29:     0x5649638365d8 - aptos::genesis::GenesisTool::execute::{{closure}}::he27d9b78c186269f
                               at /home/user/projects/aptos-core/crates/aptos/src/genesis/mod.rs:51:76
  30:     0x5649638315e1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd3634bea5f03d8fb
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  31:     0x564963834e6f - aptos::Tool::execute::{{closure}}::hc130d8808baef7c6
                               at /home/user/projects/aptos-core/crates/aptos/src/lib.rs:54:44
  32:     0x56496382c571 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h19682278222f4a17
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  33:     0x5649638092f2 - aptos::main::{{closure}}::hd212248d33b4ea29
                               at /home/user/projects/aptos-core/crates/aptos/src/main.rs:17:41
  34:     0x56496382e7fb - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h69cae3b1feffa3e9
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/future/mod.rs:91:19
  35:     0x564963825ca0 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h74e3ef6f85b74504
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  36:     0x564963833140 - tokio::coop::with_budget::{{closure}}::hd04a3108cdd9d5a8
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  37:     0x564963824916 - std::thread::local::LocalKey<T>::try_with::h476934ec528d41e1
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:445:16
  38:     0x56496382473d - std::thread::local::LocalKey<T>::with::hb6982dde6db92506
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/thread/local.rs:421:9
  39:     0x564963825b30 - tokio::coop::with_budget::h045f07a92550c693
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  40:     0x564963825b30 - tokio::coop::budget::h4a0cc17f61b11c4d
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  41:     0x564963825b30 - tokio::park::thread::CachedParkThread::block_on::hbb3af0d7c6b7015b
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  42:     0x564963809613 - tokio::runtime::enter::Enter::block_on::h06d3d1df0297aba9
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  43:     0x564963822a4f - tokio::runtime::thread_pool::ThreadPool::block_on::h5ba0fe48bcb937b0
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/mod.rs:90:9
  44:     0x5649637ff5b6 - tokio::runtime::Runtime::block_on::hd9a4a70bb96a9284
                               at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/mod.rs:482:43
  45:     0x5649637da859 - aptos::main::h24471a259b72175e
                               at /home/user/projects/aptos-core/crates/aptos/src/main.rs:20:5
  46:     0x5649637ff65b - core::ops::function::FnOnce::call_once::h1aebe9e81d73ffbe
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
  47:     0x5649638090ee - std::sys_common::backtrace::__rust_begin_short_backtrace::h1646935a316c83b0
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:122:18
  48:     0x564963825d71 - std::rt::lang_start::{{closure}}::he4dcfc9b6209a789
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:145:18
  49:     0x56496a7cb12e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5f1ba3b861cac230
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
  50:     0x56496a7cb12e - std::panicking::try::do_call::h4febfdb770eca39d
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  51:     0x56496a7cb12e - std::panicking::try::h8b0eac8a7d726dbf
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  52:     0x56496a7cb12e - std::panic::catch_unwind::h11b83c489c0d8394
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  53:     0x56496a7cb12e - std::rt::lang_start_internal::{{closure}}::h63502d2988634103
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
  54:     0x56496a7cb12e - std::panicking::try::do_call::h4be475cff12d2aae
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
  55:     0x56496a7cb12e - std::panicking::try::h1a3b25b8eaf9ba31
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
  56:     0x56496a7cb12e - std::panic::catch_unwind::h224588ada67b9b0b
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
  57:     0x56496a7cb12e - std::rt::lang_start_internal::h2807b375c1959759
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
  58:     0x564963825d40 - std::rt::lang_start::h5c76101b83984a5f
                               at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:144:17
  59:     0x5649637da90c - main
  60:     0x7f9b0a806083 - __libc_start_main
  61:     0x5649637c75fe - _start
  62:                0x0 - <unknown>
```

**Comment by stevekeol** [comment]
Any body fixed it ???

**Comment by wrwg** [comment]
The systems has much changed since then, so not sure to say. Please reopen if you see the issue again.
