### ISSUE TITLE
[Bug] Code fragment in genesis.move breaks prover

### ISSUE THREAD

**Issue by rafales** [aptos-labs/aptos-core#3844]
# 🐛 Bug

Including `aptos_framework::coin` in my code causes the move prover to panic with the following error:

```
thread 'tokio-runtime-worker' panicked at 'not implemented: Not yet supported constant vector type: Vector(Primitive(Address))', /Users/rafal/.cargo/git/checkouts/move-0639dd674f581c30/f204998/language/move-prover/bytecode/src/stackless_bytecode_generator.rs:1274:30
```

It seems that using `vector<address>` is not supported. And it seems that the code that is actually triggering the problem lives in `genesis.move`. It's this fragment:

```move
        let framework_reserved_addresses = vector<address>[@0x2, @0x3, @0x4, @0x5, @0x6, @0x7, @0x8, @0x9, @0x10];
        let i = 0;
        while (!vector::is_empty(&framework_reserved_addresses)){
            let address = vector::pop_back<address>(&mut framework_reserved_addresses);
            let (aptos_account, framework_signer_cap) = account::create_framework_reserved_account(address);
            aptos_governance::store_signer_cap(&aptos_account, address, framework_signer_cap);
            i = i+1;
        };
```

When I commented out this code prover worked normally.

## To reproduce

```move
module tables::Donation {
    use std::error;
    use std::signer::address_of;
    use aptos_framework::coin;

    const DONATION_LEDGER: u64 = 1;

    struct DonationLedger<phantom CoinType> has key {

    }

    spec schema AbortsUnlessAcceptsDonations<CoinType> {
        addr: address;
        aborts_if exists<DonationLedger<CoinType>>(addr);
        aborts_with error::already_exists(DONATION_LEDGER);
    }

    public entry fun accept_donations<CoinType>(account: &signer) {
        check_accepts_donations<CoinType>(address_of(account));
        move_to(account, DonationLedger<CoinType>{});
    }

    fun check_accepts_donations<CoinType>(addr: address) {
        assert!(!exists<DonationLedger<CoinType>>(addr), error::already_exists(DONATION_LEDGER));
    }

    spec check_accepts_donations {
        pragma aborts_if_is_strict = false;
    }

    public entry fun accepts_donations<CoinType>(addr: address): bool {
        exists<DonationLedger<CoinType>>(addr)
    }

    spec accept_donations {
        let addr = address_of(account);
        include AbortsUnlessAcceptsDonations<CoinType>;
        ensures accepts_donations<CoinType>(addr);
        ensures old(accepts_donations<CoinType>(addr)) == false;
    }

    public fun donate_coin<CoinType>(to: address, coin: coin::Coin<CoinType>) {
        check_accepts_donations<CoinType>(to);
        coin::destroy_zero(coin);
    }

    spec module {
        pragma aborts_if_is_strict = true;
    }
}
```

**Stack trace/error message**

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   3: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   4: move_stackless_bytecode::stackless_bytecode_generator::StacklessBytecodeGenerator::generate_bytecode
   5: move_stackless_bytecode::stackless_bytecode_generator::StacklessBytecodeGenerator::generate_function
   6: move_stackless_bytecode::function_target_pipeline::FunctionTargetsHolder::add_target
   7: move_prover::create_and_process_bytecode
   8: move_prover::run_move_prover_with_model
   9: move_cli::base::prove::run_move_prover
  10: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: tokio::runtime::blocking::pool::Inner::run
```

## Expected Behavior

Prover finishes running with either success or failure.

## System information

CLI: 0.3.3

## Additional context

Prover is ran with `aptos move prover`

**Comment by rafales** [comment]
It seems that this has already been addressed in move repository: https://github.com/move-language/move/pull/411

**Comment by gregnazario** [comment]
@junkil-park let's make sure your changes get into our CLI

Thanks for calling this out @rafales

**Comment by junkil-park** [comment]
@rafales, thank you for reporting this. This should have been fixed in the Aptos CLI by now. Please feel free to reopen the issue if not. Thank you!

**Comment by rafales** [comment]
It works now. Thanks @junkil-park!
