### ISSUE TITLE
[Bug] Typescript SDK unusable due to Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by 0xys** [aptos-labs/aptos-core#3848]
# 🐛 Bug
[Official example code](https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/typescript/sdk/examples/typescript) is meant to be run in `aptos-core` repository, which is not practical. But, porting off the directory and run the same code as an independent project produces the error `Error: Cannot find module 'tslib'`.

## To reproduce
package.json
```
{
  "name": "sdk-ts-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "ts-node index.ts"
  },
  "license": "MIT",
  "dependencies": {
    "aptos": "^1.3.9",
    "dotenv": "^16.0.1"
  },
  "devDependencies": {
    "@types/node": "^18.6.2",
    "npm-run-all": "^4.1.5",
    "ts-node": "^10.9.1",
    "typescript": "4.7.4"
  }
}
```

And `transfer_coin.ts` in [example](https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/typescript/sdk/examples/typescript) is renamed to `index.ts` .

**Code snippet to reproduce**
```
$ yarn run start
```

**Stack trace/error message**
```
yarn run v1.22.18
$ ts-node index.ts
Error: Cannot find module 'tslib'
Require stack:
- /home/username/projects/sdk-ts-test/node_modules/aptos/dist/aptos.cjs.development.js
- /home/username/projects/sdk-ts-test/node_modules/aptos/dist/index.js
- /home/username/projects/sdk-ts-test/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/username/projects/sdk-ts-test/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/username/projects/sdk-ts-test/node_modules/aptos/dist/aptos.cjs.development.js:11:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .js] (/home/username/projects/sdk-ts-test/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/username/projects/sdk-ts-test/node_modules/aptos/dist/aptos.cjs.development.js',
    '/home/username/projects/sdk-ts-test/node_modules/aptos/dist/index.js',
    '/home/username/projects/sdk-ts-test/index.ts'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected Behavior
Same result as run inside aptos-core repo.

## System information
Ubuntu 20.04 on WSL2

## Additional context
Folder structure
- sdk-ts-test
   - node_modules
   - common.ts   // exact copy of [common.ts](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/examples/typescript/common.ts)
   - index.ts         // exact copy of [transfer_coin.ts](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/examples/typescript/transfer_coin.ts)
   - package.json
   - tsconfig.json
   - yarn.lock

**Comment by jjleng** [comment]
have you tried to clean up node_modules and reinstall the dependencies?

**Comment by tin-snowflake** [comment]
This can be resolved by installing tslib in your project 'npm install tslib'

**Comment by jjleng** [comment]
solved.

**Comment by 0xys** [comment]
Thanks. it's solved.
