### ISSUE TITLE
[Bug][indexer] when indexing devnet, it stucked and panic at version 27883805

### ISSUE THREAD

**Issue by nolanxyg** [aptos-labs/aptos-core#4184]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
1. install the indexer(commit-id: 4d525ce)
2. run the indexer to index devnet
3. it will panic and stuck when indexing version 27883805(the version was got from error log, see blow)
```

**Stack trace/error message**
```
// Paste the output here
2022-09-14T09:01:42.513403Z [main] INFO src/main.rs:91 Starting indexer... {"processor_name":"default_processor"}
2022-09-14T09:01:42.513425Z [main] INFO src/main.rs:93 Created the inspection service...  {"processor_name":"default_processor"}
2022-09-14T09:01:42.513711Z [main] INFO src/main.rs:100 Created the connection pool...  {"processor_name":"default_processor"}
2022-09-14T09:01:42.559866Z [main] INFO src/main.rs:106 Instantiating tailer...  {"processor_name":"default_processor"}
2022-09-14T09:01:42.564340Z [main] INFO src/main.rs:122 Running migrations... {"processor_name":"default_processor"}
2022-09-14T09:01:42.564360Z [main] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/tailer.rs:54 Running migrations...
2022-09-14T09:01:42.568027Z [main] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/tailer.rs:63 Migrations complete!
2022-09-14T09:02:01.635862Z [main] INFO src/main.rs:136 Setting starting version... {"processor_name":"default_processor","start_version":27880305}
2022-09-14T09:02:01.635903Z [main] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/tailer.rs:119 Will start fetching from version {"version":27880305}
2022-09-14T09:02:01.635907Z [main] INFO src/main.rs:143 Starting fetcher... {"processor_name":"default_processor"}
2022-09-14T09:02:01.635928Z [main] INFO src/main.rs:148 Indexing loop started! {"processor_name":"default_processor"}
2022-09-14T09:02:01.635932Z [main] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/tailer.rs:68 Checking if chain id is correct
2022-09-14T09:02:01.656787Z [main] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/tailer.rs:91 Chain id matches! Continuing to index chain {"chain_id":27}
2022-09-14T09:02:01.945295Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/fetcher.rs:74 Found new highest known version {"highest_known_version":28736006}
2022-09-14T09:02:01.945319Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/fetcher.rs:89 Preparing to fetch transactions {"current_version":27880305,"highest_known_version":28736006,"num_batches":10,"num_missing":855701}
2022-09-14T09:02:02.800471Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 300ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:02:03.337212Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 600ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:02:04.172890Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 1200ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:02:05.626503Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 2400ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:02:08.277613Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 4800ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:02:13.329444Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 9600ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:02:23.180541Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 19200ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:02:42.639546Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 38400ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:03:21.259041Z [tokio-runtime-worker] INFO /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/crates/aptos-rest-client/src/lib.rs:1137 Failed to call API, retrying in 76800ms: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
2022-09-14T09:04:38.060973Z [tokio-runtime-worker] ERROR /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/fetcher.rs:166 Could not fetch 500 transactions starting at 27883805. Err: Unknown(error decoding response body: invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053

Caused by:
    invalid struct tag: 0x330d5618fc92f3dfb09b965e047d4fc1a3ef382afc1a58ce9b8cafa58a5bd88a::vector::VectorStore, expected name, got VectorType at line 1 column 2072053)
thread 'tokio-runtime-worker' panicked at 'Could not fetch 500 transactions starting at 27883805 in 120000ms!', /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/fetcher.rs:170:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'No transactions, producer of batches died', /usr/local/cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/4d525ce/ecosystem/indexer/src/indexer/fetcher.rs:211:14
```

## Expected Behavior

It shouldn't panic and stuck there.

## System information

**Please complete the following information:**
- 
- 
-

**Comment by nolanxyg** [comment]
Besides we should fix the bug, could it be better to tolerate the error(record it in db) and continue indexing?

**Comment by nolanxyg** [comment]
another bug: indexer stuck because of another error @bowenyang007 
```
2022-09-15T03:30:14.668479Z [main] INFO src/main.rs:74 Starting indexer...
2022-09-15T03:30:14.725107Z [main] INFO src/main.rs:77 Created the connection pool... 
2022-09-15T03:30:14.725388Z [main] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:43 Running migrations...
2022-09-15T03:30:14.726535Z [main] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:52 Migrations complete!
2022-09-15T03:30:14.726559Z [main] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:57 Checking if chain id is correct
2022-09-15T03:30:18.849540Z [main] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:80 Chain id matches! Continuing to index chain 27
2022-09-15T03:30:18.849658Z [main] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:97 Adding processor to indexer: default_processor
2022-09-15T03:30:18.849714Z [main] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:169 Will start fetching from version 30180000
2022-09-15T03:30:18.849750Z [main] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:104 Checking for previously errored versions...
2022-09-15T03:30:18.886694Z [tokio-runtime-worker] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:112 Found 0 previously errored versions for default_processor
2022-09-15T03:30:18.886870Z [main] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/tailer.rs:141 Fixing previously errored versions complete!
2022-09-15T03:30:18.886914Z [main] INFO src/main.rs:112 Starting fetcher...
2022-09-15T03:30:18.886991Z [main] INFO src/main.rs:117 Indexing loop started!
2022-09-15T03:30:20.120262Z [tokio-runtime-worker] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/ecosystem/indexer/src/indexer/fetcher.rs:71 Found 33257966 as the new highest known version
2022-09-15T03:30:27.910375Z [main] INFO src/main.rs:132 Indexer has processed version 30180500. Overall average TPS: 55
2022-09-15T03:30:28.019945Z [main] INFO src/main.rs:132 Indexer has processed version 30181000. Overall average TPS: 109
2022-09-15T03:30:28.294740Z [main] INFO src/main.rs:132 Indexer has processed version 30182000. Overall average TPS: 212
2022-09-15T03:30:28.390729Z [tokio-runtime-worker] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/crates/aptos-rest-client/src/lib.rs:1056 Failed to call API, retrying in 1000ms: Api(AptosErrorResponse { error: AptosError { message: "Failed to convert transaction data from storage", error_code: InternalError, vm_error_code: None }, state: Some(State { chain_id: 27, epoch: 72, version: 33258426, timestamp_usecs: 1663212627495958, oldest_ledger_version: 0, oldest_block_height: 0, block_height: 5798527 }), status_code: 500 })
2022-09-15T03:30:28.514967Z [main] INFO src/main.rs:132 Indexer has processed version 30183000. Overall average TPS: 311
2022-09-15T03:30:28.736277Z [main] INFO src/main.rs:132 Indexer has processed version 30184000. Overall average TPS: 406
2022-09-15T03:30:28.978534Z [main] INFO src/main.rs:132 Indexer has processed version 30185000. Overall average TPS: 495
2022-09-15T03:30:30.229700Z [tokio-runtime-worker] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/crates/aptos-rest-client/src/lib.rs:1056 Failed to call API, retrying in 2000ms: Api(AptosErrorResponse { error: AptosError { message: "Failed to convert transaction data from storage", error_code: InternalError, vm_error_code: None }, state: Some(State { chain_id: 27, epoch: 72, version: 33258574, timestamp_usecs: 1663212629578147, oldest_ledger_version: 0, oldest_block_height: 0, block_height: 5798549 }), status_code: 500 })
2022-09-15T03:30:32.982019Z [tokio-runtime-worker] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/crates/aptos-rest-client/src/lib.rs:1056 Failed to call API, retrying in 4000ms: Api(AptosErrorResponse { error: AptosError { message: "Failed to convert transaction data from storage", error_code: InternalError, vm_error_code: None }, state: Some(State { chain_id: 27, epoch: 72, version: 33258773, timestamp_usecs: 1663212632235435, oldest_ledger_version: 0, oldest_block_height: 0, block_height: 5798576 }), status_code: 500 })
2022-09-15T03:30:37.367117Z [tokio-runtime-worker] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/crates/aptos-rest-client/src/lib.rs:1056 Failed to call API, retrying in 8000ms: Api(AptosErrorResponse { error: AptosError { message: "Failed to convert transaction data from storage", error_code: InternalError, vm_error_code: None }, state: Some(State { chain_id: 27, epoch: 72, version: 33259089, timestamp_usecs: 1663212636779980, oldest_ledger_version: 0, oldest_block_height: 0, block_height: 5798625 }), status_code: 500 })
2022-09-15T03:30:45.752297Z [tokio-runtime-worker] INFO /Users/nolan/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/8f634bc/crates/aptos-rest-client/src/lib.rs:1056 Failed to call API, retrying in 16000ms: Api(AptosErrorResponse { error: AptosError { message: "Failed to convert transaction data from storage", error_code: InternalError, vm_error_code: None }, state: Some(State { chain_id: 27, epoch: 72, version: 33259654, timestamp_usecs: 1663212645165354, oldest_ledger_version: 0, oldest_block_height: 0, block_height: 5798716 }), status_code: 500 })
^C
```

**Comment by davidiw** [comment]
Closing out, please re-open if the issue persists.

**Comment by Astrapolis-peasant** [comment]
The same error happens again for version 5743447 of devnet. 
Invalid entry function ID 0xfa258453e05d09a4e354e060ad6bbde2bdd6e230bb9f5594a84fc717a5c53606::Faucet::claim<CoinType> at line 1 column 187701)

**Comment by davidiw** [comment]
@Astrapolis-peasant this is the indexer?

**Comment by Astrapolis-peasant** [comment]
> 

Yes, pretty much the same error as previously mentioned due to the API parsing

**Comment by Astrapolis-peasant** [comment]
@davidiw any updates?
