### ISSUE TITLE
[Bug] aptos core failed to deserialize multi signed transaction

### ISSUE THREAD

**Issue by peekpi** [aptos-labs/aptos-core#4307]
# 🐛 Bug

We are testing multi signed transaction.
In most case, it works fine.
However, in a few cases, the node will throw an error: `'Failed to deserialize input into SignedTransaction'`.
The multi signed transaction is build by aptos js-sdk, and can be deserialized by the js-sdk. 
I guess the error comes from here:
https://github.com/aptos-labs/aptos-core/blob/971c160079263a8d3e1d2503a570b01ecaaf10ba/api/src/transactions.rs#L662-L679
## To reproduce
Save the following code to `test.js`, and run `node test.js`. 
Should use the latest js-sdk, because there are minor bugs(#3635 ) of deserialization in earlier versions of the js-sdk.
```js
const {TxnBuilderTypes, BCS, AptosClient} = require("aptos");

async function main() {
    const bcsTx = Buffer.from('ded69107503162ee2d001edea6435dabdb1872f862cf366c16947d8781478701000000000000000002e5a6f272ee8517ca39d83715d14cb733e285853e924c3a3b8d6d59d9acab50aa0d6d6f6d656e74756d5f7361666508726567697374657200010c0b57616c6c65742074657374881300000000000001000000000000000293b839010000001f0161841a1ca8e47f78c03dc4ec61eb7a6f1aba5f3e4235389a20e7018388bf631f7d50081a3900885a635bf480d27827c71ff55d06fbc6f1e9fb737d49b758df81ec020000000000000000000000000000000000000000000000000000000000000002840113bc18fcb89a04ec0eb6618e5c3df55b833c21fb2be8f63beacea751ee9d4faa7f7b2c544498408dbb6208fcb37e0ddc3034a6d0d865dc1e7d57d31496018609fe602c38aaeb31661c90637f728cc6f2d97cbe14e390f03bf70c041173182dc7a912a88f195d0eb5b6d25460bf75ec3ee9ac021c9c85bd5f42d9d963e2fe2d0ec0000000', 'hex');
    const multiTx = TxnBuilderTypes.SignedTransaction.deserialize(new BCS.Deserializer(bcsTx));
    console.log(multiTx);

    console.log('\n\nsumbit signed multi transaction...');
    const client = new AptosClient('https://fullnode.devnet.aptoslabs.com/v1');
    await client.submitSignedBCSTransaction(bcsTx);
}

main();

```

**error message**
```
ApiError: Bad Request
    at catchErrorCodes (/Users/xxx/github/aptos/mvp/momentum-safe-mvp/node_modules/aptos/dist/generated/core/request.js:221:15)
    at /Users/xxx/github/aptos/mvp/momentum-safe-mvp/node_modules/aptos/dist/generated/core/request.js:252:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  url: 'https://fullnode.devnet.aptoslabs.com/v1/transactions',
  status: 400,
  statusText: 'Bad Request',
  body: {
    message: 'Failed to deserialize input into SignedTransaction',
    error_code: 'invalid_input',
    vm_error_code: null
  },
  request: {
    url: '/transactions',
    method: 'POST',
    body: Buffer(369) [Uint8Array] [
      222, 214, 145,   7,  80,  49,  98, 238,  45,   0,  30, 222,
      166,  67,  93, 171, 219,  24, 114, 248,  98, 207,  54, 108,
       22, 148, 125, 135, 129,  71, 135,   1,   0,   0,   0,   0,
        0,   0,   0,   0,   2, 229, 166, 242, 114, 238, 133,  23,
      202,  57, 216,  55,  21, 209,  76, 183,  51, 226, 133, 133,
       62, 146,  76,  58,  59, 141, 109,  89, 217, 172, 171,  80,
      170,  13, 109, 111, 109, 101, 110, 116, 117, 109,  95, 115,
       97, 102, 101,   8, 114, 101, 103, 105, 115, 116, 101, 114,
        0,   1,  12,  11,
      ... 269 more items
    ],
    mediaType: 'application/x.aptos.signed_transaction+bcs'
  }
}
```

**Comment by davidiw** [comment]
Can you provide input of failing transactions? We have proptest on these interfaces, so it would be great to determine where this is happening.

**Comment by peekpi** [comment]
> Can you provide input of failing transactions? We have proptest on these interfaces, so it would be great to determine where this is happening.
 
yeah, the serialized transaction is:
```
ded69107503162ee2d001edea6435dabdb1872f862cf366c16947d8781478701000000000000000002e5a6f272ee8517ca39d83715d14cb733e285853e924c3a3b8d6d59d9acab50aa0d6d6f6d656e74756d5f7361666508726567697374657200010c0b57616c6c65742074657374881300000000000001000000000000000293b839010000001f0161841a1ca8e47f78c03dc4ec61eb7a6f1aba5f3e4235389a20e7018388bf631f7d50081a3900885a635bf480d27827c71ff55d06fbc6f1e9fb737d49b758df81ec020000000000000000000000000000000000000000000000000000000000000002840113bc18fcb89a04ec0eb6618e5c3df55b833c21fb2be8f63beacea751ee9d4faa7f7b2c544498408dbb6208fcb37e0ddc3034a6d0d865dc1e7d57d31496018609fe602c38aaeb31661c90637f728cc6f2d97cbe14e390f03bf70c041173182dc7a912a88f195d0eb5b6d25460bf75ec3ee9ac021c9c85bd5f42d9d963e2fe2d0ec0000000
```
can be found it in the produce js script.

**Comment by davidiw** [comment]
do you have the source on how that was produced?

**Comment by gregnazario** [comment]
Hi, I see you've given the serialized transaction.  Is it possible for you to give us the inputs and process to get there?  Thanks!

**Comment by peekpi** [comment]
> Hi, I see you've given the serialized transaction. Is it possible for you to give us the inputs and process to get there? Thanks!

like this:
```js
const {TxnBuilderTypes, BCS, AptosClient } = require("aptos");

function buildMultiTxn() {
    const payload = new TxnBuilderTypes.TransactionPayloadEntryFunction(
        TxnBuilderTypes.EntryFunction.natural(
            '0xe5a6f272ee8517ca39d83715d14cb733e285853e924c3a3b8d6d59d9acab50aa::momentum_safe',
            'register',
            [],
            [BCS.bcsSerializeStr('Wallet test')],
        ),
    );
    const txn = new TxnBuilderTypes.RawTransaction(
        TxnBuilderTypes.AccountAddress.fromHex('0xded69107503162ee2d001edea6435dabdb1872f862cf366c16947d8781478701'),
        0n, // sn
        payload,
        5000n, // max gas
        1n, // gas price
        5263364866n, // expiration
        new TxnBuilderTypes.ChainId(31),
    );

    const publicKeys = [
        new TxnBuilderTypes.Ed25519PublicKey(Buffer.from('841a1ca8e47f78c03dc4ec61eb7a6f1aba5f3e4235389a20e7018388bf631f7d', 'hex')),
        new TxnBuilderTypes.Ed25519PublicKey(Buffer.from('50081a3900885a635bf480d27827c71ff55d06fbc6f1e9fb737d49b758df81ec', 'hex')),
        new TxnBuilderTypes.Ed25519PublicKey(Buffer.from('0200000000000000000000000000000000000000000000000000000000000000', 'hex')),
    ];
    const multiPublicKeys = new TxnBuilderTypes.MultiEd25519PublicKey(publicKeys, 2);
    const signatures = [
        new TxnBuilderTypes.Ed25519Signature(Buffer.from('13bc18fcb89a04ec0eb6618e5c3df55b833c21fb2be8f63beacea751ee9d4faa7f7b2c544498408dbb6208fcb37e0ddc3034a6d0d865dc1e7d57d31496018609', 'hex')),
        new TxnBuilderTypes.Ed25519Signature(Buffer.from('fe602c38aaeb31661c90637f728cc6f2d97cbe14e390f03bf70c041173182dc7a912a88f195d0eb5b6d25460bf75ec3ee9ac021c9c85bd5f42d9d963e2fe2d0e', 'hex')),
    ];
    const sigBitmap = TxnBuilderTypes.MultiEd25519Signature.createBitmap([0,1]);
    const multiSignature = new TxnBuilderTypes.MultiEd25519Signature(signatures, sigBitmap);
    const authenticator = new TxnBuilderTypes.TransactionAuthenticatorMultiEd25519(multiPublicKeys, multiSignature);

    return new TxnBuilderTypes.SignedTransaction(txn, authenticator);
}

async function main() {
    const txn = buildMultiTxn();
    const serializedTxn = BCS.bcsToBytes(txn);
    const bcsTx = Buffer.from('ded69107503162ee2d001edea6435dabdb1872f862cf366c16947d8781478701000000000000000002e5a6f272ee8517ca39d83715d14cb733e285853e924c3a3b8d6d59d9acab50aa0d6d6f6d656e74756d5f7361666508726567697374657200010c0b57616c6c65742074657374881300000000000001000000000000000293b839010000001f0161841a1ca8e47f78c03dc4ec61eb7a6f1aba5f3e4235389a20e7018388bf631f7d50081a3900885a635bf480d27827c71ff55d06fbc6f1e9fb737d49b758df81ec020000000000000000000000000000000000000000000000000000000000000002840113bc18fcb89a04ec0eb6618e5c3df55b833c21fb2be8f63beacea751ee9d4faa7f7b2c544498408dbb6208fcb37e0ddc3034a6d0d865dc1e7d57d31496018609fe602c38aaeb31661c90637f728cc6f2d97cbe14e390f03bf70c041173182dc7a912a88f195d0eb5b6d25460bf75ec3ee9ac021c9c85bd5f42d9d963e2fe2d0ec0000000', 'hex');
    console.log('equal:', Buffer.from(serializedTxn).toString('hex') == bcsTx.toString('hex'));
    const multiTx = TxnBuilderTypes.SignedTransaction.deserialize(new BCS.Deserializer(bcsTx));
    console.log(multiTx);
    console.log('\n\nsumbit signed multi transaction...');
    const client = new AptosClient('https://fullnode.devnet.aptoslabs.com/v1');
    await client.submitSignedBCSTransaction(bcsTx);
}

main();
```

**Comment by jjleng** [comment]
`0200000000000000000000000000000000000000000000000000000000000000` is not a valid public key. At least https://docs.rs/ed25519-dalek/latest/ed25519_dalek cannot parse it. Closing the issue.
