### ISSUE TITLE
[Bug crates/indexer] Insert Ownerships table sometime crashed.

### ISSUE THREAD

**Issue by LevenSton** [aptos-labs/aptos-core#4376]
# 🐛 Bug

## To reproduce
Branch: devnet
Commit-id: 971c160079263a8d3e1d2503a570b01ecaaf10ba / Revert "Revert "[Networking] Remove unicode support from dns names.""
Build command:  cargo build --bin aptos-node --release --features "indexer"

**Code snippet to reproduce**
```rust
# Your code goes here
cargo build --bin aptos-node --release --features "indexer"
./aptos-node --config ./fullnode.yaml
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
2022-09-20T08:51:59.448415Z [indexer] WARN crates/indexer/src/database.rs:57 Error running query: DatabaseError(__Unknown, "value for domain uint_64 violates check constraint \"uint_64_check\"")
INSERT INTO "ownerships" ("ownership_id", "token_id", "owner", "amount", "updated_at", "inserted_at") VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT ("ownership_id") DO UPDATE SET "amount" = ("ownerships"."amount" + $7) -- binds: ["0xb09e7ba73f42e7b8f3295d74999a4bcb36aac0b9b2355a4704b034e84385bbd::Alice's::Alice's first token::0::0xb09e7ba73f42e7b8f3295d74999a4bcb36aac0b9b2355a4704b034e84385bbd", "0xb09e7ba73f42e7b8f3295d74999a4bcb36aac0b9b2355a4704b034e84385bbd::Alice's::Alice's first token::0", "0xb09e7ba73f42e7b8f3295d74999a4bcb36aac0b9b2355a4704b034e84385bbd", BigDecimal("0"), 2022-09-16T02:28:29, 2022-09-20T08:51:59.447746056, BigDecimal("-1")]
2022-09-20T08:51:59.474457Z [indexer] INFO crates/indexer/src/indexer/tailer.rs:155 Finished processing of transaction batch {"end_version":12999,"num_txns":500,"start_version":12500,"time_millis":75}
2022-09-20T08:51:59.474492Z [indexer] INFO crates/indexer/src/runtime.rs:246 Processed batch version {"batch_end_version":12999,"batch_start_version":12500,"processor_name":"token_processor","tps":12795,"versions_processed":13000}
2022-09-20T08:51:59.477278Z [indexer] INFO crates/indexer/src/indexer/tailer.rs:155 Finished processing of transaction batch {"end_version":14499,"num_txns":500,"start_version":14000,"time_millis":78}
2022-09-20T08:51:59.478774Z [indexer] INFO crates/indexer/src/indexer/tailer.rs:155 Finished processing of transaction batch {"end_version":13499,"num_txns":500,"start_version":13000,"time_millis":79}
2022-09-20T08:51:59.478801Z [indexer] INFO crates/indexer/src/runtime.rs:246 Processed batch version {"batch_end_version":14499,"batch_start_version":14000,"processor_name":"token_processor","tps":13235,"versions_processed":13500}
2022-09-20T08:51:59.478809Z [indexer] INFO crates/indexer/src/runtime.rs:246 Processed batch version {"batch_end_version":13499,"batch_start_version":13000,"processor_name":"token_processor","tps":13725,"versions_processed":14000}
2022-09-20T08:51:59.551928Z [indexer] INFO crates/indexer/src/indexer/tailer.rs:155 Finished processing of transaction batch {"end_version":14999,"num_txns":500,"start_version":14500,"time_millis":74}
2022-09-20T08:51:59.551972Z [indexer] INFO crates/indexer/src/runtime.rs:246 Processed batch version {"batch_end_version":14999,"batch_start_version":14500,"processor_name":"token_processor","tps":13266,"versions_processed":14500}
2022-09-20T08:51:59.553389Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:279 Fetched transactions {"actual_last_version":17499,"num_transactions":500,"starting_version":17000,"time_millis":154}
2022-09-20T08:51:59.566678Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:279 Fetched transactions {"actual_last_version":16999,"num_transactions":500,"starting_version":16500,"time_millis":167}
2022-09-20T08:51:59.577451Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:279 Fetched transactions {"actual_last_version":16499,"num_transactions":500,"starting_version":16000,"time_millis":178}
2022-09-20T08:51:59.585853Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:279 Fetched transactions {"actual_last_version":15499,"num_transactions":500,"starting_version":15000,"time_millis":186}
2022-09-20T08:51:59.615128Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:279 Fetched transactions {"actual_last_version":15999,"num_transactions":500,"starting_version":15500,"time_millis":140}
2022-09-20T08:51:59.615462Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:141 Finished fetching transaction batches {"fetch_millis":216,"num_batches":5,"versions_fetched":2500}
2022-09-20T08:51:59.615480Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:170 Finished sending transaction batches {"num_batches":5,"send_millis":0,"versions_sent":2500}
2022-09-20T08:51:59.615488Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:106 Preparing to fetch transactions {"current_version":17500,"highest_known_version":1967154,"num_batches":5,"num_missing":1949654}
2022-09-20T08:51:59.676041Z [indexer] ERROR crates/crash-handler/src/lib.rs:39 details = '''panicked at 'Error update token ownership: DatabaseError(__Unknown, "value for domain uint_64 violates check constraint \"uint_64_check\"")', crates/indexer/src/processors/token_processor.rs:172:6'''
backtrace = '''
   0:     0x555defb09147 - backtrace::backtrace::libunwind::trace::hf0cf5374a03fa9d1
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
```

## System information

**Please complete the following information:**
- 
- 
- rustc 1.63.0 (4b91a6ea7 2022-08-08)
- 
ubuntu 20.04

**Comment by davidiw** [comment]
Please re-open if the issue persists. The indexer is going under rapid development right now.
