### ISSUE TITLE
[Bug] sdk/typescript: Uncaught (in promise) TypeError: Cannot assign to read only property 'then' of object '[object Promise]' 

### ISSUE THREAD

**Issue by wk3368** [aptos-labs/aptos-core#4604]
# 🐛 Bug

I am working on my wallet chrome extension to support aptos  blockchain using aptos typescript sdk , but got this error while trying to call any aptos client apis.

```
CancelToken.js:38 Uncaught (in promise) TypeError: Cannot assign to read only property 'then' of object '[object Promise]' 
```

## To reproduce

**Code snippet to reproduce**
```typescript

import { AptosClient } from 'aptos';

export default class SendTransactionScreen extends Component {
  ...
  constructor(props) {
    super(props);
    this.client = new AptosClient('https://fullnode.devnet.aptoslabs.com/v1');
  }
  
  componentDidUpdate(prevProps) {
    this.client.getChainId().then((number) => {
      console.log({ number })
    });
  }
  ...
}
```

**Stack trace/error message**
```
// Paste the output here
```

![image](https://user-images.githubusercontent.com/171268/192825071-23c84824-b460-45b3-8ff4-d9acdebeca06.png)

at new CancelToken (CancelToken.js:38:1)
![image](https://user-images.githubusercontent.com/171268/192825297-3ac4104b-d393-49fe-92d3-6cd14c3ef485.png)

at Function.source (CancelToken.js:110:1)
![image](https://user-images.githubusercontent.com/171268/192825427-42bf4762-034f-4119-ad34-3b062f904f64.png)

at sendRequest (index.js:780:1)
![image](https://user-images.githubusercontent.com/171268/192825583-86005c17-2d24-49c8-9d9d-6d8ed1d9ab9e.png)

the associated source code should be this line:
https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/generated/core/request.ts#L303

at index.js:846:1
![image](https://user-images.githubusercontent.com/171268/192826024-70af9170-b27a-4aba-a670-dcb46bbacf42.png)
the associated source code should be this line:
https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/src/generated/core/request.ts#L390

## Expected Behavior

according to axios doc: https://axios-http.com/docs/cancellation
`CancelToken` is deprecated since 0.22.0, and we are using 0.27.2.
maybe it should be replaced by `AbortController`

## System information

**Please complete the following information:**
 
1.13.14

## Additional context

package.json
```
{
  "name": "xxx",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "setup": "yarn install && yarn setup:postinstall",
    "setup:postinstall": "yarn patch-package && yarn allow-scripts",
    "start": "node development/build/index.js dev",
    "start:lavamoat": "yarn build dev",
    "dist": "yarn build prod",
    "build": "lavamoat development/build/index.js",
    "start:test": "yarn build testDev",
    "build:test": "yarn build test",
    "devtools:react": "react-devtools",
    "devtools:redux": "remotedev --hostname=localhost --port=8100",
    "generate:migration": "./development/generate-migration.sh",
    "start:dev": "concurrently -k -n build,react,redux yarn:start yarn:devtools:react yarn:devtools:redux"
  },
  "resolutions": {
    "**/regenerator-runtime": "^0.13.7",
    "**/configstore/dot-prop": "^5.1.1",
    "**/ethers/elliptic": "^6.5.4",
    "**/knex/minimist": "^1.2.5",
    "**/optimist/minimist": "^1.2.5",
    "**/socketcluster/minimist": "^1.2.5",
    "**/redux/symbol-observable": "^2.0.3",
    "**/redux-devtools-instrument/symbol-observable": "^2.0.3",
    "**/rxjs/symbol-observable": "^2.0.3",
    "analytics-node/axios": "^0.21.1",
    "netmask": "^2.0.1",
    "pull-ws": "^3.3.2"
  },
  "dependencies": {
    "@babel/runtime": "^7.5.5",
    "@download/blockies": "^1.0.3",
    "@formatjs/intl-relativetimeformat": "^5.2.6",
    "@fortawesome/fontawesome-free": "^5.13.0",
    "@lavamoat/preinstall-always-fail": "^1.0.0",
    "@material-ui/core": "^4.11.0",
    "@metamask/controllers": "^6.2.1",
    "@metamask/eth-ledger-bridge-keyring": "^0.3.0",
    "@metamask/etherscan-link": "^2.0.0",
    "@metamask/jazzicon": "^2.0.0",
    "@metamask/logo": "^2.5.0",
    "@metamask/obs-store": "^5.0.0",
    "@popperjs/core": "^2.4.0",
    "@reduxjs/toolkit": "^1.5.0",
    "@sentry/browser": "^5.26.0",
    "@sentry/integrations": "^5.26.0",
    "@starcoin/contract-metadata": "^0.6.0",
    "@starcoin/starcoin": "^1.9.0",
    "@starcoin/stc-block-tracker": "^0.1.0",
    "@starcoin/stc-inpage-provider": "^0.3.4",
    "@starcoin/stc-json-rpc": "^0.1.0",
    "@starcoin/stc-json-rpc-middleware": "^0.2.0",
    "@starcoin/stc-keyring-controller": "^1.6.0",
    "@starcoin/stc-multisign-keyring": "^0.4.1",
    "@starcoin/stc-nonce-tracker": "^0.2.0",
    "@starcoin/stc-onekey-keyring": "^1.2.0",
    "@starcoin/stc-query": "^0.3.1",
    "@starcoin/stc-util": "^0.3.0",
    "@zxing/library": "^0.8.0",
    "abortcontroller-polyfill": "^1.4.0",
    "analytics-node": "^3.4.0-beta.3",
    "aptos": "^1.3.14",
    "await-semaphore": "^0.1.1",
    "bignumber.js": "^4.1.0",
    "bn.js": "^4.11.7",
    "classnames": "^2.2.6",
    "content-hash": "^2.5.2",
    "copy-to-clipboard": "^3.0.8",
    "currency-formatter": "^1.4.2",
    "debounce-stream": "^2.0.0",
    "deep-freeze-strict": "1.1.1",
    "end-of-stream": "^1.4.4",
    "eth-ens-namehash": "^2.0.8",
    "eth-json-rpc-filters": "^4.2.1",
    "eth-json-rpc-infura": "^5.1.0",
    "eth-method-registry": "^2.0.0",
    "eth-phishing-detect": "^1.1.14",
    "eth-rpc-errors": "^4.0.2",
    "eth-sig-util": "^3.0.0",
    "ethereum-ens-network-map": "^1.0.2",
    "ethereumjs-abi": "^0.6.4",
    "ethereumjs-tx": "1.3.7",
    "ethereumjs-util": "5.1.0",
    "ethereumjs-wallet": "^0.6.4",
    "ethers": "^5.0.8",
    "ethjs": "^0.4.0",
    "ethjs-contract": "^0.2.3",
    "ethjs-ens": "^2.0.0",
    "extension-port-stream": "^2.0.0",
    "extensionizer": "^1.0.1",
    "fast-json-patch": "^2.0.4",
    "fast-safe-stringify": "^2.0.7",
    "fuse.js": "^3.2.0",
    "globalthis": "^1.0.1",
    "human-standard-token-abi": "^2.0.0",
    "immer": "^8.0.1",
    "json-rpc-engine": "^6.1.0",
    "json-rpc-middleware-stream": "^2.1.1",
    "jsonschema": "^1.2.4",
    "labeled-stream-splicer": "^2.0.2",
    "localforage": "^1.9.0",
    "lodash": "^4.17.19",
    "loglevel": "^1.4.1",
    "luxon": "^1.24.1",
    "nanoid": "^2.1.6",
    "nonce-tracker": "^1.0.0",
    "obj-multiplex": "^1.0.0",
    "pify": "^5.0.0",
    "post-message-stream": "^3.0.0",
    "promise-to-callback": "^1.0.0",
    "prop-types": "^15.6.1",
    "pubnub": "4.27.3",
    "pump": "^3.0.0",
    "punycode": "^2.1.1",
    "qrcode-generator": "1.4.1",
    "react": "^16.12.0",
    "react-dnd": "^3.0.2",
    "react-dnd-html5-backend": "^7.4.4",
    "react-dom": "^16.12.0",
    "react-idle-timer": "^4.2.5",
    "react-inspector": "^2.3.0",
    "react-popper": "^2.2.3",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.1.2",
    "react-simple-file-input": "^2.0.0",
    "react-tippy": "^1.2.2",
    "react-toggle-button": "^2.2.0",
    "react-transition-group": "^1.2.1",
    "readable-stream": "^2.3.3",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "reselect": "^3.0.1",
    "rpc-cap": "^3.2.1",
    "safe-event-emitter": "^1.0.1",
    "ses": "^0.12.4",
    "single-call-balance-checker-abi": "^1.0.0",
    "swappable-obj-proxy": "^1.1.0",
    "textarea-caret": "^3.0.1",
    "unicode-confusables": "^0.1.1",
    "valid-url": "^1.0.9",
    "web3": "^0.20.7",
    "web3-stream-provider": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.1",
    "@babel/eslint-parser": "^7.12.1",
    "@babel/eslint-plugin": "^7.12.1",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.10.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.5.5",
    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.5.5",
    "@lavamoat/allow-scripts": "^1.0.4",
    "@metamask/eslint-config": "^5.0.0",
    "@metamask/forwarder": "^1.1.0",
    "@metamask/test-dapp": "^4.0.1",
    "@sentry/cli": "^1.58.0",
    "@storybook/addon-actions": "^6.1.17",
    "@storybook/addon-backgrounds": "^6.1.17",
    "@storybook/addon-knobs": "^6.1.17",
    "@storybook/addon-toolbars": "^6.1.17",
    "@storybook/core": "^6.1.17",
    "@storybook/react": "^6.1.17",
    "@storybook/storybook-deployer": "^2.8.7",
    "@testing-library/react": "^10.4.8",
    "@testing-library/react-hooks": "^3.2.1",
    "@types/react": "^16.9.53",
    "addons-linter": "1.14.0",
    "babelify": "^10.0.0",
    "brfs": "^2.0.2",
    "browserify": "^16.5.1",
    "chalk": "^3.0.0",
    "chromedriver": "94.0.0",
    "concurrently": "^5.2.0",
    "copy-webpack-plugin": "^6.0.3",
    "cross-spawn": "^7.0.3",
    "css-loader": "^2.1.1",
    "del": "^3.0.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.15.1",
    "eslint": "^7.7.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-mocha": "^8.0.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "~7.20.0",
    "eslint-plugin-react-hooks": "^4.0.4",
    "fancy-log": "^1.3.3",
    "fast-glob": "^3.2.2",
    "fs-extra": "^8.1.0",
    "ganache-cli": "^6.12.1",
    "ganache-core": "^2.13.1",
    "geckodriver": "^1.21.0",
    "get-port": "^5.1.0",
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^5.0.0",
    "gulp-livereload": "4.0.0",
    "gulp-rename": "^2.0.0",
    "gulp-rtlcss": "^1.4.0",
    "gulp-sass": "^4.1.0",
    "gulp-sourcemaps": "^2.6.0",
    "gulp-stylelint": "^13.0.0",
    "gulp-terser-js": "^5.2.2",
    "gulp-watch": "^5.0.1",
    "gulp-zip": "^4.0.0",
    "jsdom": "^11.2.0",
    "koa": "^2.7.0",
    "lavamoat": "^5.1.4",
    "lavamoat-viz": "^6.0.4",
    "lockfile-lint": "^4.0.0",
    "loose-envify": "^1.4.0",
    "mocha": "^7.2.0",
    "nock": "^9.0.14",
    "node-fetch": "^2.6.1",
    "nyc": "^15.0.0",
    "patch-package": "^6.4.7",
    "polyfill-crypto.getrandomvalues": "^1.0.0",
    "prettier": "^2.1.1",
    "prettier-plugin-sort-json": "^0.0.1",
    "proxyquire": "^2.1.3",
    "randomcolor": "^0.5.4",
    "rc": "^1.2.8",
    "react-devtools": "^4.10.1",
    "read-installed": "^4.0.3",
    "redux-mock-store": "^1.5.4",
    "remote-redux-devtools": "^0.5.16",
    "resolve-url-loader": "^3.1.2",
    "sass": "^1.32.4",
    "sass-loader": "^10.1.1",
    "selenium-webdriver": "4.0.0-alpha.7",
    "serve-handler": "^6.1.2",
    "sinon": "^9.0.0",
    "source-map": "^0.7.2",
    "source-map-explorer": "^2.4.2",
    "string.prototype.matchall": "^4.0.2",
    "style-loader": "^0.21.0",
    "stylelint": "^13.6.1",
    "through2": "^2.0.3",
    "ttest": "^2.1.1",
    "vinyl-buffer": "^1.0.1",
    "vinyl-source-stream": "^2.0.0",
    "watchify": "^3.11.1",
    "webpack": "^4.41.6"
  },
  "engines": {
    "node": "^14.15.1",
    "yarn": "^1.16.0"
  },
  "lavamoat": {
    "allowScripts": {
      "node-sass": true,
      "chromedriver": true,
      "geckodriver": true,
      "@sentry/cli": true,
      "electron": true,
      "core-js": false,
      "core-js-pure": false,
      "keccak": false,
      "secp256k1": false,
      "web3": false,
      "sha3": false,
      "bufferutil": false,
      "utf-8-validate": false,
      "leveldown": false,
      "ursa-optional": false,
      "gc-stats": false,
      "github:assemblyscript/assemblyscript": false,
      "tiny-secp256k1": false,
      "@lavamoat/preinstall-always-fail": false,
      "fsevents": false,
      "scrypt": false,
      "postinstall-postinstall": false
    }
  }
}

```

babel.config.js
```
module.exports = function (api) {
  api.cache(false);
  return {
    presets: [
      [
        '@babel/preset-env',
        {
          targets: {
            browsers: ['chrome >= 63', 'firefox >= 68'],
          },
        },
      ],
      '@babel/preset-react',
    ],
    plugins: [
      '@babel/plugin-transform-runtime',
      '@babel/plugin-proposal-class-properties',
      '@babel/plugin-proposal-object-rest-spread',
      '@babel/plugin-proposal-optional-chaining',
      '@babel/plugin-proposal-nullish-coalescing-operator',
    ],
  };
};
```

**Comment by wk3368** [comment]
PR： https://github.com/aptos-labs/aptos-core/pull/4629
