### ISSUE TITLE
[Bug] Move transactional-test fails due to can't found aptos-core 

### ISSUE THREAD

**Issue by element2050** [aptos-labs/aptos-core#4634]
# 🐛 Bug

When i run transactional test in my project, error occur like this:

aptos move transactional-test  --root-path  transactional-tests --filter math_test

running 1 tests
thread 'tests::test/math_test.move' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory '/Users/runner/work/aptos-core/aptos-core/aptos-move/framework/move-stdlib/sources'', aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs:287:63

@gregnazario 

## To reproduce
**Code snippet to reproduce**
```move
//# init --addresses test=0x4a0caec13e8d1a25b87405f5edf6cbfd30bd36b6f331888c8f950e425bf6b9c7 --initial-coins 1000000000

//# create_account —name alice --initial-coins 100000000


//# publish
module alice::TestHelper {
    const EXP_SCALE: u128 = 10000000000;// e10

    const U64_MAX:u64 = 18446744073709551615;  //length(U64_MAX)==20
    const U128_MAX:u128 = 340282366920938463463374607431768211455;  //length(U128_MAX)==39
}
// check: EXECUTED


//# run --signers alice
script {
    use aptos_std::math64;
    use aptos_std::debug;

    use test::SafeMath;

    // case : x*y/z overflow
    fun math_overflow(_: signer) {
        let precision: u8 = 18;
        let scaling_factor = math64::pow(10, (precision as u64));
        let amount_x: u128 = 110000 * scaling_factor;
        let reserve_y: u128 = 8000000 * scaling_factor;
        let reserve_x: u128 = 2000000 * scaling_factor;

        let amount_y_1 = test::safe_mul_div_u128(amount_x, reserve_y, reserve_x);
        let amount_y_2 = test::safe_mul_div_u128(amount_x, reserve_x, reserve_y);
        debug::print<u128>(&amount_y_1);
        debug::print<u128>(&amount_y_2);
        assert!(amount_y_1 == 440000 * scaling_factor, 3003);
        assert!(amount_y_2 == 27500 * scaling_factor, 3004);
    }
}
// check: EXECUTED

```

**Stack trace/error message**
```
thread 'tests::test/token_test.move' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory '/Users/runner/work/aptos-core/aptos-core/aptos-move/framework/move-stdlib/sources'', aptos-move/aptos-transactional-test-harness/src/aptos_test_harness.rs:287:63
stack backtrace:
   0:        0x10ecd44d9 - __mh_execute_header
   1:        0x10e35bd3b - __mh_execute_header
   2:        0x10eca66c8 - __mh_execute_header
   3:        0x10ecd7a5d - __mh_execute_header
   4:        0x10ecd8944 - __mh_execute_header
   5:        0x10ecd8424 - __mh_execute_header
   6:        0x10ecd8399 - __mh_execute_header
   7:        0x10ecd8355 - __mh_execute_header
   8:        0x10f1c0e53 - __ZN7rocksdb6ribbon6detail34BandingConfigHelper1MaybeSupportedILNS0_25ConstructionFailureChanceE1ELy128ELb0ELb0ELb1EE11GetNumSlotsEj
```

## Expected Behavior
transaction test not fail

## System information

**Please complete the following information:**
- devnet
- aptos --version
aptos 0.3.5
- MacOS 12.6

## Additional context

Move.toml config
```
[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "7d58019a9ce08ca5242bda16e221047cb82ff7b9", subdir = "aptos-move/framework/aptos-framework"}
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "7d58019a9ce08ca5242bda16e221047cb82ff7b9", subdir = "aptos-move/framework/aptos-stdlib"}
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "7d58019a9ce08ca5242bda16e221047cb82ff7b9", subdir = "aptos-move/framework/move-stdlib"}
```

**Comment by wrwg** [comment]
We should consider removing the feature of transactional tests
