### ISSUE TITLE
undo able run validator

### ISSUE THREAD

**Issue by fengland** [aptos-labs/aptos-core#4993]
hi :
   when i want to run vfn(validator & validator full node),i get the wrong out put,did any one know how to fix  it
and i have refer the page:https://aptos.dev/nodes/validator-node/operator/running-validator-node/run-validator-node-using-source
the wrong output is occurred at step 12

best regard

2022-10-12T12:58:46.236613Z [main] INFO storage/schemadb/src/lib.rs:168 Opened RocksDB. {"rocksdb_name":"ledger_db"}
2022-10-12T12:58:46.248421Z [main] INFO storage/schemadb/src/lib.rs:168 Opened RocksDB. {"rocksdb_name":"state_merkle_db"}
2022-10-12T12:58:46.248581Z [main] INFO storage/aptosdb/src/pruner/db_pruner.rs:17 state_merkle_pruner initialized. {"min_readable_version":0}
2022-10-12T12:58:46.248680Z [main] INFO storage/aptosdb/src/pruner/db_pruner.rs:17 state_merkle_pruner initialized. {"min_readable_version":0}
2022-10-12T12:58:46.253551Z [main] INFO storage/aptosdb/src/state_store/mod.rs:395 StateStore initialization finished. {"latest_in_memory_root_hash":"6e9c67140e4e2ae27e6b1b2b1f6f7b9f07d89fc89068632fa937ea46de9e0153","latest_in_memory_version":0,"latest_snapshot_root_hash":"6e9c67140e4e2ae27e6b1b2b1f6f7b9f07d89fc89068632fa937ea46de9e0153","latest_snapshot_version":0}
2022-10-12T12:58:46.254678Z [main] INFO storage/aptosdb/src/pruner/db_pruner.rs:17 ledger_pruner initialized. {"min_readable_version":0}
2022-10-12T12:58:46.255030Z [main] INFO storage/aptosdb/src/lib.rs:375 Opened AptosDB (LedgerDB + StateMerkleDB). {"ledger_db_path":"/opt/aptos/data/db/ledger_db","state_merkle_db_path":"/opt/aptos/data/db/state_merkle_db","time_ms":"51"}
2022-10-12T12:58:46.257000Z [main] INFO storage/backup/backup-service/src/lib.rs:43 Backup service spawned.
details = '''panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', config/src/config/network_config.rs:232:89'''
backtrace = '''
   0:     0x5608a7eb7a37 - backtrace::backtrace::libunwind::trace::hdf0a9ecc27845667
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h4bf1ea2607f51092
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h80107bfa2faf16ba
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x5608a7eb8975 - backtrace::capture::Backtrace::create::h6689c347508e6d3b
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h94268c4eac14c92d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22

**Comment by fengland** [comment]
the error out say can't find file  onfig/src/config/network_config.rs,but i can find the file in directory.
see below:

![image](https://user-images.githubusercontent.com/31641981/195354648-1531ee00-d18b-43ab-bb16-a3bded80f9b3.png)

**Comment by gregnazario** [comment]
https://github.com/aptos-labs/aptos-core/blob/main/config/src/config/network_config.rs#L232-L257

This is a bad message, but you're missing your network identity file

https://github.com/aptos-labs/aptos-core/blob/main/docker/compose/aptos-node/validator.yaml#L33-L35
