### ISSUE TITLE
[Bug][indexer] when indexing testnet, it stucked and panic at version:286297910

### ISSUE THREAD

**Issue by Lredhdx** [aptos-labs/aptos-core#5151]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
1. install the indexer(commit-id: [be96c79](https://github.com/node-real/aptos-indexer-node/pull/17/commits/be96c79b5c70711d144780480b84132d016a83fe))
2. run the indexer to index testnet
3. it will panic and stuck when indexing version 286297910(the version was got from error log, see blow)
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
2022-10-19T09:00:47.503822Z [network-Pub-13] INFO network/src/connectivity_manager/mod.rs:727 [full_node,Public,cb6f3cf6] pubkey sets updated for peer: 28dde00b, pubkeys: [{x25519::PublicKey(11593b0a139a373cbbb646b5f848bcd5ccf23a95f953eaa3f94130dd4b1b1a51)}, {}, {}] {"discovery_source":"OnChainValidatorSet","network_context":{"role":"full_node","network_id":"Public","peer_id":"cb6f3cf6ad07c3bd38732d6294cd4370f4bc496798ace80ec2b04eb13ba08030"},"remote_peer":"28dde00b49a2c5ec8b46a1fbd855afd0fac64ea347a3dffc803ad672e7810186"}
2022-10-19T09:00:47.503835Z [network-Pub-13] INFO network/src/connectivity_manager/mod.rs:742 [full_node,Public,cb6f3cf6] addresses updated for peer: 28dde00b, update src: OnChainValidatorSet, addrs: [[/dns/fullnode.testnet.aptos.movemove.org/tcp/6182/noise-ik/0x11593b0a139a373cbbb646b5f848bcd5ccf23a95f953eaa3f94130dd4b1b1a51/handshake/0], [], []] {"network_addresses":[["/dns/fullnode.testnet.aptos.movemove.org/tcp/6182/noise-ik/0x11593b0a139a373cbbb646b5f848bcd5ccf23a95f953eaa3f94130dd4b1b1a51/handshake/0"],[],[]],"network_context":{"role":"full_node","network_id":"Public","peer_id":"cb6f3cf6ad07c3bd38732d6294cd4370f4bc496798ace80ec2b04eb13ba08030"},"remote_peer":"28dde00b49a2c5ec8b46a1fbd855afd0fac64ea347a3dffc803ad672e7810186"}
details = '''panicked at 'Could not convert 14 txn from OnChainTransactions starting at 286297910: invalid utf-8 sequence of 1 bytes from index 1', crates/indexer/src/indexer/fetcher.rs:309:13'''
backtrace = '''
   0:     0x561524d96077 - backtrace::backtrace::libunwind::trace::hf59b97827a414887
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::hfc9ee46e651fa90a
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h8eedbfc2548bb5d8
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x561524d83d45 - backtrace::capture::Backtrace::create::h9f4acde781be3f2a
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h0326af951968e3fe
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x5615232cae7a - crash_handler::handle_panic::h8d2ba083e9e0db3b
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::he8869f8738070511
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:27:9
   3:     0x561524df4c3a - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
   4:     0x561524df4a77 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
   5:     0x561524df3334 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
   6:     0x561524df47a9 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   7:     0x561522aa1533 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   8:     0x5615234a81be - aptos_indexer::indexer::fetcher::fetch_nexts::{{closure}}::h1657c5ba42c2e147
                               at /usr/src/indexer-node/crates/indexer/src/indexer/fetcher.rs:309:13
2022-10-19T09:00:47.503846Z [network-Pub-13] INFO network/src/connectivity_manager/mod.rs:727 [full_node,Public,cb6f3cf6] pubkey sets updated for peer: 828ca971, pubkeys: [{x25519::PublicKey(657c1ce875959e2ad84f25a28547021c5c905291a75c39d2b940b512e20ccf2b)}, {}, {}] {"discovery_source":"OnChainValidatorSet","network_context":{"role":"full_node","network_id":"Public","peer_id":"cb6f3cf6ad07c3bd38732d6294cd4370f4bc496798ace80ec2b04eb13ba08030"},"remote_peer":"828ca971e35c8b9a807439e5a328fdc9a5ed0efbfb12f40bc451d17f6998be3f"}
2022-10-19T09:00:47.503858Z [network-Pub-13] INFO network/src/connectivity_manager/mod.rs:742 [full_node,Public,cb6f3cf6] addresses updated for peer: 828ca971, update src: OnChainValidatorSet, addrs: [[/dns/fullnode1.testnet.aptoslabs.com/tcp/6182/noise-ik/0x657c1ce875959e2ad84f25a28547021c5c905291a75c39d2b940b512e20ccf2b/handshake/0], [], []] {"network_addresses":[["/dns/fullnode1.testnet.aptoslabs.com/tcp/6182/noise-ik/0x657c1ce875959e2ad84f25a28547021c5c905291a75c39d2b940b512e20ccf2b/handshake/0"],[],[]],"network_context":{"role":"full_node","network_id":"Public","peer_id":"cb6f3cf6ad07c3bd38732d6294cd4370f4bc496798ace80ec2b04eb13ba08030"},"remote_peer":"828ca971e35c8b9a807439e5a328fdc9a5ed0efbfb12f40bc451d17f6998be3f"}
2022-10-19T09:00:47.503864Z [network-Pub-13] INFO network/src/connectivity_manager/mod.rs:727 [full_node,Public,cb6f3cf6] pubkey sets updated for peer: d1af3b6a, pubkeys: [{x25519::PublicKey(08d5e275d038af3ac8d5aa6675eb3dbfe6b5f65c079532223ed485b480b11e1b)}, {}, {}] {"discovery_source":"OnChainValidatorSet","network_context":{"role":"full_node","network_id":"Public","peer_id":"cb6f3cf6ad07c3bd38732d6294cd4370f4bc496798ace80ec2b04eb13ba08030"},"remote_peer":"d1af3b6a77458f90cf4207beb14e8df7cccd08db2896b59037807736aad8a376"}
2022-10-19T09:00:47.503873Z [network-Pub-13] INFO network/src/connectivity_manager/mod.rs:742 [full_node,Public,cb6f3cf6] addresses updated for peer: d1af3b6a, update src: OnChainValidatorSet, addrs: [[/ip4/8.213.133.242/tcp/6182/noise-ik/0x08d5e275d038af3ac8d5aa6675eb3dbfe6b5f65c079532223ed485b480b11e1b/handshake/0], [], []] {"network_addresses":[["/ip4/8.213.133.242/tcp/6182/noise-ik/0x08d5e275d038af3ac8d5aa6675eb3dbfe6b5f65c079532223ed485b480b11e1b/handshake/0"],[],[]],"network_context":{"role":"full_node","network_id":"Public","peer_id":"cb6f3cf6ad07c3bd38732d6294cd4370f4bc496798ace80ec2b04eb13ba08030"},"remote_peer":"d1af3b6a77458f90cf4207beb14e8df7cccd08db2896b59037807736aad8a376"}
2022-10-19T09:00:47.504366Z [sync-driver-13] INFO state-sync/state-sync-v2/state-sync-driver/src/driver.rs:178 {"message":"Started the state sync v2 driver!","name":"driver"}
2022-10-19T09:00:47.515237Z [main] INFO api/src/runtime.rs:154 Not using TLS for API
```

## Expected Behavior
It shouldn't panic and stuck there.

## System information

**Please complete the following information:**
- 
- 
-

**Comment by mohammadfarari1360** [comment]
Ok

**Comment by stopWarByWar** [comment]
and aptos-node branch and commit is 
`mainnet: 86b29874ff68bece908494a8c54ea35ac2cb0c43`

**Comment by davidiw** [comment]
we have updates in main, mainnet, and testnet to address this, please update.
