### ISSUE TITLE
[Indexer]Mainnet. crash Indexer module

### ISSUE THREAD

**Issue by LevenSton** [aptos-labs/aptos-core#5174]
# 🐛 Bug

## To reproduce
Mainnet Indexer crash！
**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
2022-10-20T09:09:43.599406Z [indexer] ERROR crates/crash-handler/src/lib.rs:39 details = '''panicked at 'Could not convert 500 txn from OnChainTransactions starting at 4990500: invalid utf-8 sequence of 1 bytes from index 8', crates/indexer/src/indexer/fetcher.rs:301:13'''
backtrace = '''
   0:     0x555f80cb12e7 - backtrace::backtrace::libunwind::trace::hf59b97827a414887
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::hfc9ee46e651fa90a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h8eedbfc2548bb5d8
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x555f80cb2265 - backtrace::capture::Backtrace::create::h9f4acde781be3f2a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h0326af951968e3fe
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by davidiw** [comment]
We have updates in main, mainnet, and testnet to address this issue, please update your node.
