### ISSUE TITLE
[Bug][indexer] when indexing mainnet, it stucked and panic at version:7602763

### ISSUE THREAD

**Issue by Lredhdx** [aptos-labs/aptos-core#5218]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
1. install the indexer(commit-id: [7195a33f51849e7e3d23a652bb3fa3241e77f04a])
2. run the indexer to index mainnet
3. it will panic and stuck when indexing version 7602863(the version was got from error log, see blow)
```

**Stack trace/error message**
```
euw1c-ccn-aptos-mainnet-api2.jumpisolated.com/tcp/6182/noise-ik/0xe51632cf8004506fff126942cda2a3e0fe6b8ca1edaac4e1fa5a5383a2b3f037/handshake/0"],[],[]],"network_context":{"role":"full_node","network_id":"Public","peer_id":"efd4b8bafbf5cbf31d149ca06fd23d9eb92c46416b2f1a7cf4645af333410a5c"},"remote_peer":"b87476d8877cfc324a520cef4d0cd6e42e26ec3ce613a8127220e2e444561e16"}
2022-10-22T09:04:30.827540Z [sync-driver-5] INFO state-sync/state-sync-v2/state-sync-driver/src/driver.rs:178 {"message":"Started the state sync v2 driver!","name":"driver"}
2022-10-22T09:04:30.836740Z [main] INFO api/src/runtime.rs:154 Not using TLS for API
2022-10-22T09:04:30.836815Z [main] INFO api/src/runtime.rs:204 Poem is running at 0.0.0.0:8080, behind the reverse proxy at the API port
2022-10-22T09:04:30.838228Z [api-14] INFO  {"addr":"socket://0.0.0.0:8080","message":"listening"}
2022-10-22T09:04:30.838240Z [api-14] INFO  {"message":"server started"}
2022-10-22T09:04:30.838343Z [indexer] INFO crates/indexer/src/runtime.rs:117 Starting indexer... {"processor_name":"default_processor"}
2022-10-22T09:04:30.838360Z [indexer] INFO crates/indexer/src/runtime.rs:120 Creating connection pool... {"processor_name":"default_processor"}
2022-10-22T09:04:30.839038Z [main] INFO aptos-move/aptos-vm/src/aptos_vm.rs:95 Adapter created for Validation {"name":"miscellaneous","txn_id":0}
details = '''panicked at 'Could not parse timestamp 14644241486006389464 for version 7602763', crates/indexer/src/util.rs:44:28'''
backtrace = '''
   0:     0x56097bdc0c37 - backtrace::backtrace::libunwind::trace::h08a7da9328a1c8ce
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h8607ae60c9066b6d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::hca58773009926646
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x56097bdcc195 - backtrace::capture::Backtrace::create::he5e9d882b1c7fda4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h49b8ddb15461416c
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x56097a14f88a - crash_handler::handle_panic::hb095cc651dc1ccf1
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::h1d0e23635c45ff7f
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:27:9
   3:     0x56097be2c33a - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:702:17
   4:     0x56097be2c177 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
   5:     0x56097be2a9c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
   6:     0x56097be2bea9 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   7:     0x56097be4df33 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   8:     0x56097a185818 - aptos_indexer::util::parse_timestamp_secs::{{closure}}::h963e20b37baebdd6
                               at /usr/src/indexer-node/crates/indexer/src/util.rs:44:28
                           core::option::Option<T>::unwrap_or_else::ha73060c4a0519973
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:825:21
                           aptos_indexer::util::parse_timestamp_secs::hfbf0b35aa869b60a
                               at /usr/src/indexer-node/crates/indexer/src/util.rs:43:5
                           aptos_indexer::models::user_transactions::UserTransaction::from_transaction::h4eb84cb157f74890
                               at /usr/src/indexer-node/crates/indexer/src/models/user_transactions.rs:81:44
2022-10-22T09:04:30.839557Z [shared-mem-15] INFO mempool/src/shared_mempool/coordinator.rs:53 {"event":"start","name":"coordinator_runtime"}
2022-10-22T09:04:30.839597Z [shared-mem-15] INFO mempool/src/shared_mempool/coordinator.rs:208 {"event":"received","name":"reconfig_update"}
2022-10-22T09:04:30.839634Z [shared-mem-15] INFO mempool/src/shared_mempool/tasks.rs:507 {"event":"process","name":"reconfig_update","reconfig_update":"OnChainConfigPayload [epoch: 112, configs: OnChain config ID [address: 0x1, identifier: version]OnChain config ID [address: 0x1, identifier: consensus_config]OnChain config ID [address: 0x1, identifier: aptos_governance]OnChain config ID [address: 0x1, identifier: stake]]"}
2022-10-22T09:04:30.839644Z [shared-mem-15] INFO aptos-move/aptos-vm/src/aptos_vm.rs:95 Adapter created for Validation {"name":"miscellaneous","txn_id":0}
2022-10-22T09:04:30.894546Z [indexer] INFO crates/indexer/src/runtime.rs:125 Created the connection pool...  {"processor_name":"default_processor"}
2022-10-22T09:04:30.894567Z [indexer] INFO crates/indexer/src/runtime.rs:130 Instantiating tailer...  {"processor_name":"default_processor"}
2022-10-22T09:04:30.894582Z [indexer] INFO crates/indexer/src/runtime.rs:152 Running migrations... {"processor_name":"default_processor"}
2022-10-22T09:04:30.898193Z [indexer] INFO crates/indexer/src/runtime.rs:156 Fetching starting version from db... {"processor_name":"default_processor"}
2022-10-22T09:04:30.900219Z [indexer] INFO crates/indexer/src/runtime.rs:175 Setting starting version... {"final_start_version":7602762,"processor_name":"default_processor","start_version_from_config":null,"starting_version_from_db":7602762}
2022-10-22T09:04:30.900230Z [indexer] INFO crates/indexer/src/indexer/tailer.rs:112 Will start fetching from version {"version":7602762}
2022-10-22T09:04:30.900232Z [indexer] INFO crates/indexer/src/runtime.rs:184 Starting fetcher... {"processor_name":"default_processor"}
2022-10-22T09:04:30.900253Z [indexer] INFO crates/indexer/src/runtime.rs:187 Indexing loop started! {"processor_name":"default_processor","start_version":7602762}
2022-10-22T09:04:30.900258Z [indexer] INFO crates/indexer/src/indexer/tailer.rs:62 Checking if chain id is correct {"processor_name":"default_processor"}
2022-10-22T09:04:30.902867Z [indexer] INFO crates/indexer/src/indexer/tailer.rs:80 Chain id matches! Continue to index... {"chain_id":1,"processor_name":"default_processor"}
2022-10-22T09:04:30.902867Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:74 Found new highest known version {"highest_known_version":7602766}
2022-10-22T09:04:30.902873Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:95 Preparing to fetch transactions {"current_version":7602762,"highest_known_version":7602766,"max_batch_size":500}
2022-10-22T09:04:30.910572Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:320 Fetched transactions {"actual_last_version":7602766,"num_transactions":5,"starting_version":7602762,"time_millis":7}
2022-10-22T09:04:30.910703Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:138 Finished fetching transaction batches {"fetch_millis":7,"num_batches":1,"versions_fetched":5}
2022-10-22T09:04:30.910717Z [indexer] INFO crates/indexer/src/indexer/fetcher.rs:167 Finished sending transaction batches {"num_batches":1,"send_millis":0,"versions_sent":5}
2022-10-22T09:04:30.990250Z [telemetry-15] INFO crates/aptos-telemetry/src/service.rs:201 Telemetry service started!
2022-10-22T09:04:31.048866Z [indexer] ERROR crates/crash-handler/src/lib.rs:39 details = '''panicked at 'Could not parse timestamp 14644241486006389464 for version 7602763', crates/indexer/src/util.rs:44:28'''
backtrace = '''
   0:     0x56097bdc0c37 - backtrace::backtrace::libunwind::trace::h08a7da9328a1c8ce
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h8607ae60c9066b6d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::hca58773009926646
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x56097bdcc195 - backtrace::capture::Backtrace::create::he5e9d882b1c7fda4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h49b8ddb15461416c
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x56097a14f88a - crash_handler::handle_panic::hb095cc651dc1ccf1
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::h1d0e23635c45ff7f
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:27:9
   3:     0x56097be2c33a - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:702:17
   4:     0x56097be2c177 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
   5:     0x56097be2a9c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
   9:     0x56097a31607c - aptos_indexer::models::transactions::Transaction::from_transaction::h0a0b724a5a55a98d
                               at /usr/src/indexer-node/crates/indexer/src/models/transactions.rs:121:21
  10:     0x56097a316f58 - aptos_indexer::models::transactions::Transaction::from_transactions::hce9f27f219b371ec
                               at /usr/src/indexer-node/crates/indexer/src/models/transactions.rs:244:17
  11:     0x56097a204f54 - <aptos_indexer::processors::default_processor::DefaultTransactionProcessor as aptos_indexer::indexer::transaction_processor::TransactionProcessor>::process_transactions::{{closure}}::h4152449490714216
                               at /usr/src/indexer-node/crates/indexer/src/processors/default_processor.rs:361:13
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hae962bd6acf351e4
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  12:     0x56097a1ff937 - <core::pin::Pin<P> as core::future::future::Future>::poll::heeaa18292498bc77
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/future.rs:124:9
                           aptos_indexer::indexer::transaction_processor::TransactionProcessor::process_transactions_with_status::{{closure}}::h04878b00f241cc7a
                               at /usr/src/indexer-node/crates/indexer/src/indexer/transaction_processor.rs:85:68
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7eb3b01b22618408
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  13:     0x56097a206ed7 - <core::pin::Pin<P> as core::future::future::Future>::poll::heeaa18292498bc77
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/future.rs:124:9
                           aptos_indexer::indexer::tailer::Tailer::process_next_batch::{{closure}}::hb0b45a96a15c4ca5
                               at /usr/src/indexer-node/crates/indexer/src/indexer/tailer.rs:140:60
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd4a7e25407401c18
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
                           aptos_indexer::runtime::run_forever::{{closure}}::{{closure}}::hc2901a21c6ea9933
                               at /usr/src/indexer-node/crates/indexer/src/runtime.rs:211:71
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfac52e433bd88487
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  14:     0x56097a30274c - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::hd9cc1e68b35c2b62
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h3114cf5af3f646ab
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
                           tokio::runtime::task::core::CoreStage<T>::poll::hebd620c667fab345
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
                           tokio::runtime::task::harness::poll_future::{{closure}}::h241ab9668eaa40d7
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6a48eb4874e6f980
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
  15:     0x56097a24b39a - std::panicking::try::do_call::h1d80ae648861d7b0
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
                           std::panicking::try::h95bd01a2a878e4eb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::h7ca9ddf5110747fa
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
                           tokio::runtime::task::harness::poll_future::hd466ab19b40407d2
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
                           tokio::runtime::task::harness::Harness<T,S>::poll_inner::hc44834e34e09d540
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
                           tokio::runtime::task::harness::Harness<T,S>::poll::h3e0b969c9de3da2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
```

## Expected Behavior
It shouldn't panic and stuck there.

## System information

**Please complete the following information:**
- 
- 
-

**Comment by davidiw** [comment]
We're continuously updating the indexer as we get more interesting applications in the ecosystem. Please try the latest version and update. Closing out to force conversation.

@bowenyang007
