### ISSUE TITLE
[Bug] indexer exception

### ISSUE THREAD

**Issue by flofi-dev** [aptos-labs/aptos-core#5337]
# 🐛 Bug

My indexer stops with an exception

**Stack trace/error message**
```
022-10-28T06:38:07.277542Z [indexer] ERROR crates/crash-handler/src/lib.rs:39 details = '''panicked at 'Could not parse timestamp 14644241486006389464 for version 7602763', crates/indexer/src/util.rs:44:28'''
backtrace = '''
   0:     0x55d9e3a627e7 - backtrace::backtrace::libunwind::trace::hf59b97827a414887
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::hfc9ee46e651fa90a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h8eedbfc2548bb5d8
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x55d9e3a504b5 - backtrace::capture::Backtrace::create::h9f4acde781be3f2a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h0326af951968e3fe
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x55d9e1f38afa - crash_handler::handle_panic::h8d2ba083e9e0db3b
                               at /root/aptos-core/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::he8869f8738070511
                               at /root/aptos-core/crates/crash-handler/src/lib.rs:27:9
   3:     0x55d9e3ac13ea - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
   4:     0x55d9e3ac1227 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
   5:     0x55d9e3abfae4 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
   6:     0x55d9e3ac0f59 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   7:     0x55d9e1712bb3 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   8:     0x55d9e1f8bd28 - aptos_indexer::util::parse_timestamp_secs::{{closure}}::ha49bba67c8973794
                               at /root/aptos-core/crates/indexer/src/util.rs:44:28
                           core::option::Option<T>::unwrap_or_else::hdfe32a8fd8ecb744
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:825:21
                           aptos_indexer::util::parse_timestamp_secs::h6e976e88f76d75f0
                               at /root/aptos-core/crates/indexer/src/util.rs:43:5
                           aptos_indexer::models::user_transactions::UserTransaction::from_transaction::hc04359bcc5cfb7f7
                               at /root/aptos-core/crates/indexer/src/models/user_transactions.rs:81:44
   9:     0x55d9e1f5fbbe - aptos_indexer::models::transactions::Transaction::from_transaction::h138861b0c124f027
                               at /root/aptos-core/crates/indexer/src/models/transactions.rs:122:21
  10:     0x55d9e1f60b1f - aptos_indexer::models::transactions::Transaction::from_transactions::hc5242a3a4324ea97
                               at /root/aptos-core/crates/indexer/src/models/transactions.rs:246:17
  11:     0x55d9e21018ed - <aptos_indexer::processors::default_processor::DefaultTransactionProcessor as aptos_indexer::indexer::transaction_processor::TransactionProcessor>::process_transactions::{{closure}}::h8583f1d5bb8729dc
                               at /root/aptos-core/crates/indexer/src/processors/default_processor.rs:361:13
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfeb56bd9c5bef0ac
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  12:     0x55d9e20ffcc7 - <core::pin::Pin<P> as core::future::future::Future>::poll::ha0cccebdaf130c45
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
                           aptos_indexer::indexer::transaction_processor::TransactionProcessor::process_transactions_with_status::{{closure}}::h7095669edfc41ca7
                               at /root/aptos-core/crates/indexer/src/indexer/transaction_processor.rs:85:68
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::heab8bf855e448320
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  13:     0x55d9e20e74a6 - <core::pin::Pin<P> as core::future::future::Future>::poll::ha0cccebdaf130c45
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
                           aptos_indexer::indexer::tailer::Tailer::process_next_batch::{{closure}}::h36ffe3e19fbbfb3a
                               at /root/aptos-core/crates/indexer/src/indexer/tailer.rs:150:60
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h5629560a41238c4f
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
                           aptos_indexer::runtime::run_forever::{{closure}}::{{closure}}::hf325cbdb5a5646f3
                               at /root/aptos-core/crates/indexer/src/runtime.rs:208:71
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0f1bec63b0b030e5
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
                           tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::hc45b415d3201e125
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h56fee624f6dfe0d9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
  14:     0x55d9e1f74f20 - tokio::runtime::task::core::CoreStage<T>::poll::h04c04471d3739cbb
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
                           tokio::runtime::task::harness::poll_future::{{closure}}::h2dfbf24f71bdf714
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h29753c33bfab9c08
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  15:     0x55d9e1fdf0aa - std::panicking::try::do_call::h256c36863e1d8c31
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
                           std::panicking::try::habb77954feecf55f
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::hfd9655149ae154fa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
                           tokio::runtime::task::harness::poll_future::ha367265a1c4cbb15
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
                           tokio::runtime::task::harness::Harness<T,S>::poll_inner::h690433fd674f42e3
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
                           tokio::runtime::task::harness::Harness<T,S>::poll::h7923481285014001
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  16:     0x55d9e3a362a5 - tokio::runtime::task::raw::RawTask::poll::h14a326981b59a8be
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
                           tokio::runtime::task::LocalNotified<S>::run::h298e9d44695f852d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:385:9
                           tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h9c92959b5c0029bc
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:421:13
                           tokio::coop::with_budget::{{closure}}::h210a60fbe7cd6ffc
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
                           std::thread::local::LocalKey<T>::try_with::hdc593fe32cd4e567
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
                           std::thread::local::LocalKey<T>::with::h435579e4c6f94ecd
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  17:     0x55d9e3a2d970 - tokio::coop::with_budget::h6f84a476ffa2fb43
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5
                           tokio::coop::budget::h461b70de1e81099c
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
                           tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h743367c6643514b6
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:420:9
  18:     0x55d9e3a2ceec - tokio::runtime::scheduler::multi_thread::worker::Context::run::h5ba34433b8a0a958
  19:     0x55d9e3a270b7 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::hc17faceff29f763f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:372:17
                           tokio::macros::scoped_tls::ScopedKey<T>::set::hdb43f625385b722f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/macros/scoped_tls.rs:61:9
  20:     0x55d9e3a2c749 - tokio::runtime::scheduler::multi_thread::worker::run::h2258f7cd838f0d09
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:369:5
  21:     0x55d9e3a2472c - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::ha12dc28defad1822
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:348:45
                           <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::he3f54ca3c621afd2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/task.rs:42:21
  22:     0x55d9e3a14829 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::hbbee8e74eeb27eee
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h32d8c1104d220d99
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
                           tokio::runtime::task::core::CoreStage<T>::poll::h06125c6f4576d63d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
                           tokio::runtime::task::harness::poll_future::{{closure}}::h99752056c58fabc2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h5aa9c90115997904
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
                           std::panicking::try::do_call::h14e5efbc9224aae7
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
                           std::panicking::try::h69d396faa1cae732
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::h1a79286cdc89ce76
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
                           tokio::runtime::task::harness::poll_future::hab4eead369a294e8
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
                           tokio::runtime::task::harness::Harness<T,S>::poll_inner::hc7a493ba7c9d9644
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
                           tokio::runtime::task::harness::Harness<T,S>::poll::hb407291322ce7cd3
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  23:     0x55d9e3a124c5 - tokio::runtime::task::raw::RawTask::poll::h14a326981b59a8be
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
                           tokio::runtime::task::UnownedTask<S>::run::h06d93c5fbbe43da7
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:422:9
                           tokio::runtime::blocking::pool::Task::run::h04c10ea28791cae5
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:111:9
                           tokio::runtime::blocking::pool::Inner::run::h2d53ccbdcab76869
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:346:17
  24:     0x55d9e3a18653 - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::hd6db5a72f87b1a8b
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/pool.rs:321:13
                           std::sys_common::backtrace::__rust_begin_short_backtrace::hdec5973c70f44167
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:122:18
  25:     0x55d9e3a1c18f - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h44a85b0c70a87d40
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:505:17
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2723ba013f294bbf
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
                           std::panicking::try::do_call::h1b1a8ff2c4382586
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
                           std::panicking::try::h661b7a65aac2ae17
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::h1541ebfd999dafda
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
                           std::thread::Builder::spawn_unchecked_::{{closure}}::hc48a663b766a9c88
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:504:30
                           core::ops::function::FnOnce::call_once{{vtable.shim}}::h477c73be54c051b0
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
  26:     0x55d9e3ac4ea3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1680342795a2dc08
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h45204a69827b0e83
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
                           std::sys::unix::thread::Thread::new::thread_start::h5d4e11bbda4161c8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f8204b94b43 - <unknown>
  28:     0x7f8204c26a00 - <unknown>
  29:                0x0 - <unknown>
```

## Expected Behavior

No exception

## System information

**Please complete the following information:**
- dont know - current
- cargo --version --verbose
cargo 1.63.0 (fd9c4297c 2022-07-01)
release: 1.63.0
commit-hash: fd9c4297ccbee36d39e9a79067edab0b614edb5a
commit-date: 2022-07-01
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Ubuntu 22.04 (jammy) [64-bit]
- Linux aptos-indexer 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by davidiw** [comment]
should be resolved, if not re-open.
