### ISSUE TITLE
[Bug] aptos-node panic

### ISSUE THREAD

**Issue by crazybits** [aptos-labs/aptos-core#5362]
# 🐛 Bug
aptos-node panic with the following error log

## To reproduce

issue exist on both `main` branch and `mainnet` branch. 

full node build with the following command 

> cargo build -p aptos-node --release

**Stack trace/error message**
```
2022-10-31T02:34:13.676641Z [network-Pub-0] WARN network/src/protocols/rpc/mod.rs:558 [full_node,Public,6ea82c09] Error making outbound rpc request with request_id 37 to 60b00bc1: Error: Rpc timed out {"network_context":{"role":"full_node","network_id":"Public","peer_id":"6ea82c09fb7a0012fb77e81663465fbfe033a6134fef66cfb44f8678bc0cee3a"},"remote_peer":"60b00bc1f6cda15c9cee94bab2e44dc7727701503da80d88c23c8436c4d597a4"}
details = '''panicked at 'State merkle batch commit failed.: IO error: While open a file for random read: ./fast/db/state_merkle_db/000412.sst: Too many open files', storage/aptosdb/src/state_store/state_merkle_batch_committer.rs:64:26'''
backtrace = '''
   0:        0x1064b1a90 - backtrace::backtrace::libunwind::trace::he536e5aa11341f3c
                               at /Users/crazybit/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::ha543b6680783a78e
                               at /Users/crazybit/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h2fd1c81728f0c9be
                               at /Users/crazybit/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
                           backtrace::capture::Backtrace::create::h392c16667cbe24cd
                               at /Users/crazybit/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h46a8157a1cdb502d
                               at /Users/crazybit/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   1:        0x104b9561e - crash_handler::handle_panic::h144a35e4626cdc31
                               at /Users/crazybit/develop/aptos/aptos-core/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::ha4b0b5f662d3a9cb
                               at /Users/crazybit/develop/aptos/aptos-core/crates/crash-handler/src/lib.rs:27:9
   2:        0x10650c8eb - std::panicking::rust_panic_with_hook::hd9ead35a68ccc55e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
   3:        0x10650c763 - std::panicking::begin_panic_handler::{{closure}}::h6fca91c5e1dc2f30
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
   4:        0x10650ad27 - std::sys_common::backtrace::__rust_end_short_backtrace::h4ff3025d9a0a0490
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
   5:        0x10650c43a - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   6:        0x1065f53e3 - core::panicking::panic_fmt::h3d9f795ee387ef8d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   7:        0x1065f54d5 - core::result::unwrap_failed::haca1aa19e4c34aab
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   8:        0x1052387bc - core::result::Result<T,E>::expect::h7629cd9c9bc08e34
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
                           aptosdb::state_store::state_merkle_batch_committer::StateMerkleBatchCommitter::run::h5101186a55407cdd
                               at /Users/crazybit/develop/aptos/aptos-core/storage/aptosdb/src/state_store/state_merkle_batch_committer.rs:61:21
   9:        0x1051a8e18 - aptosdb::state_store::state_snapshot_committer::StateSnapshotCommitter::new::{{closure}}::h68dbba8405c3b869
                               at /Users/crazybit/develop/aptos/aptos-core/storage/aptosdb/src/state_store/state_snapshot_committer.rs:45:17
                           std::sys_common::backtrace::__rust_begin_short_backtrace::hfe686c4f615329ce
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:122:18
  10:        0x10523f10d - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h3d1add236ec01c14
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:505:17
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2d81cdc328ad013d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
                           std::panicking::try::do_call::h5d410304683dc765
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
                           std::panicking::try::h606856364348bcc2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::he4c21a476083a882
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
                           std::thread::Builder::spawn_unchecked_::{{closure}}::h558945ec47ba57aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:504:30
                           core::ops::function::FnOnce::call_once{{vtable.shim}}::h04f060a7f1fe59f2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
  11:        0x106510197 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b6f593edb7fb044
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha3bd0a5bf4aaac12
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
                           std::sys::unix::thread::Thread::new::thread_start::hf7c5ae502e9a7ed8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
  12:     0x7ff805b3a4e1 - __pthread_start
```

## Expected Behavior

no panic

## System information

**Please complete the following information:**

- mainnet and main branch
- rustc 1.63.0 (4b91a6ea7 2022-08-08)
- MacOS Monterey

**Comment by CapCap** [comment]
You have too many open files for what you’ve configured your OS for; please set your ulimit http://woshub.com/too-many-open-files-error-linux/

**Comment by crazybits** [comment]
@CapCap 

seems it is not due to the system limit,  related setting is as below, i thing the value is big  enough.

```
launchctl limit maxfiles  
maxfiles    64000          524288
```
