### ISSUE TITLE
[Bug] Determine why `test_entry_function_with_corpus` tests are failing in Python SDK

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-core#5633]
Running just `test_entry_function_with_corpus` with some extra prints:
```
$ make test
poetry run python -m unittest discover -s aptos_sdk/ -p '*.py' -t ..
......................asdfjksadfkjakaaaaaa
RawTranasction:
    sender: 0x7deeccb1080854f499ec8b4c1b213b82c5e34b925cf6875fec02d4b77adbd2d6
    sequence_number: 11
    payload: 0x0000000000000000000000000000000000000000000000000000000000000001::coin::transfer::<[0x0000000000000000000000000000000000000000000000000000000000000001::aptos_coin::AptosCoin]>([b'-\x13=\xdd(\x1b\xb6 UX5|\xc6\xacuf\x18\x17\xe9\xaa\xea\xc3\xaf\xeb\xc3(Bu\x9c\xbf\x7f\xa9', b'\x88\x13\x00\x00\x00\x00\x00\x00'])
    max_gas_amount: 2000
    gas_unit_price: 1
    expiration_timestamps_secs: 1234567890
    chain_id: 4

klsjdaflksdaf
RawTranasction:
    sender: 0x7deeccb1080854f499ec8b4c1b213b82c5e34b925cf6875fec02d4b77adbd2d6
    sequence_number: 11
    payload: <function ModuleId.deserialize at 0x10657cee0>::::<[]>([])
    max_gas_amount: 0
    gas_unit_price: 0
    expiration_timestamps_secs: 0
    chain_id: 0

F
======================================================================
FAIL: test_entry_function_with_corpus (sdk.aptos_sdk.transactions.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dport/a/core/ecosystem/python/sdk/aptos_sdk/transactions.py", line 569, in test_entry_function_with_corpus
    self.verify_transactions(
  File "/Users/dport/a/core/ecosystem/python/sdk/aptos_sdk/transactions.py", line 698, in verify_transactions
    self.assertEqual(raw_transaction_generated, raw_transaction)
AssertionError: <sdk.aptos_sdk.transactions.RawTransaction object at 0x106595280> != <sdk.aptos_sdk.transactions.RawTransaction object at 0x1065b5190>

----------------------------------------------------------------------
Ran 23 tests in 0.003s

FAILED (failures=1)
make: [test] Error 1 (ignored)
```

**Comment by davidiw** [comment]
resolved :D
