### ISSUE TITLE
[Bug] Fullnode crash with panic

### ISSUE THREAD

**Issue by Alivers** [aptos-labs/aptos-core#6795]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
```rust
I'm using `aptoslabs/validator:mainnet_9e7800f46230d10c805129c49cb9ed528a40e25b` image rev to run my fullnode.
```

**Stack trace/error message**
```
{"level":"INFO","source":{"package":"aptosdb","file":"storage/aptosdb/src/pruner/db_pruner.rs:17"},"thread_name":"main","hostname":"aptos-fullnode-0","timestamp":"2023-02-27T14:44:56.750203Z","message":"ledger_pruner initialized.","data":{"min_readable_version":0}}
details = '''panicked at 'Node should start correctly: DB failed to open Module ModuleId { address: 8439c96ff3628733fdf664160ba34ca9506c39a4ceb62d42d51a55659fc16888, name: Identifier("z") } deserialize with error code PartialVMError { major_status: UNKNOWN_VERSION, sub_status: None, message: None, exec_state: None, indices: [], offsets: [] }', aptos-node/src/lib.rs:160:39'''
backtrace = '''
   0:     0x55e63e2be067 - backtrace::backtrace::libunwind::trace::hdf0a9ecc27845667
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h4bf1ea2607f51092
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::h80107bfa2faf16ba
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x55e63e2befa5 - backtrace::capture::Backtrace::create::h6689c347508e6d3b
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h94268c4eac14c92d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x55e63c9fbcda - crash_handler::handle_panic::he12d1f8937964072
                               at /aptos/crates/crash-handler/src/lib.rs:35:38
                           crash_handler::setup_panic_handler::{{closure}}::h85e9247d7ece76b7
                               at /aptos/crates/crash-handler/src/lib.rs:27:9
   3:     0x55e63e32f14a - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
   4:     0x55e63e32ef87 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
   5:     0x55e63e32d844 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
   6:     0x55e63e32ecb9 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   7:     0x55e63c1dd813 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   8:     0x55e63c1dd903 - core::result::unwrap_failed::hc0baa33ef8bc7db8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   9:     0x55e63c2c598d - core::result::Result<T,E>::expect::hee44ae4d86218a6d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
                           aptos_node::AptosNodeArgs::run::h8450a21900e848b8
                               at /aptos/aptos-node/src/lib.rs:160:13
  10:     0x55e63c20ed8f - aptos_node::main::hf3eef094a5b23adc
                               at /aptos/aptos-node/src/main.rs:16:5
  11:     0x55e63c20bed3 - core::ops::function::FnOnce::call_once::h57e869277bf4cd95
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
                           std::sys_common::backtrace::__rust_begin_short_backtrace::hef7312c8ae55b7ce
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:122:18
  12:     0x55e63c20bee9 - std::rt::lang_start::{{closure}}::he866f863579d1a21
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:145:18
  13:     0x55e63e3200ee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4937aaa125c8d4b2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:280:13
                           std::panicking::try::do_call::h6f5c70e8b0a34f92
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
                           std::panicking::try::h68766ba264ecf2e2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::hc36033d2f9cc04af
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
                           std::rt::lang_start_internal::{{closure}}::h78c037f4a1a28ded
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:48
                           std::panicking::try::do_call::he6e1fffda4c750ee
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
                           std::panicking::try::h48a77ddbb2f4c87a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
                           std::panic::catch_unwind::hfa809b06a550a9e7
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
                           std::rt::lang_start_internal::h4db69ed48eaca005
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:20
  14:     0x55e63c20ee88 - main
  15:     0x7fc1b2040d0a - __libc_start_main
                               at ./csu/../csu/libc-start.c:308:16
  16:     0x55e63c20a87a - _start
  17:                0x0 - <unknown>
'''

Failed to flush telemetry: Disconnected
```

## Expected Behavior

Running.

## System information

**Please complete the following information:**
- 
- Fullnode image revision:   `aptoslabs/validator:mainnet_9e7800f46230d10c805129c49cb9ed528a40e25b`
- 
- Debian x86-64

## Additional context

Before I restart the fullnode, It logs with warn: 
`Error found when driving progress of the continuous syncer`

**Comment by Alivers** [comment]
```
{"level":"ERROR","source":{"package":"state_sync_driver","file":"state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs:881"},"thread_name":"sync-driver-3","hostname":"aptos-fullnode-0","timestamp":"2023-02-27T15:56:37.254023Z","data":{"message":"Storage synchronizer error: \"Failed to commit executed chunk! Error: base_state_version Some(93388596) does not equal to the base_version Some(93390597) in buffered state with current version Some(93390598)\"","name":"storage_synchronizer"}}
```

**Comment by Alivers** [comment]
The fullnode sync stoped at `version 93319958`. After that, the transaction sync always failed.

**Comment by JoshLind** [comment]
Hi, which network are you trying to connect to, e.g., `mainnet`?

Also, why did you choose to use `aptoslabs/validator:mainnet_9e7800f46230d10c805129c49cb9ed528a40e25b`? The latest node release version is here: https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.2.6. I'd recommend using this and wiping the database before retrying.

**Comment by Alivers** [comment]
Thanks for your reply.
1. yes, I'm trying connect to mainnet.
2. The fullnode is started on 2022-10, so that time we choose the `aptoslabs/validator:mainnet_9e7800f46230d10c805129c49cb9ed528a40e25b` image version.
3. My fullnode config yaml is:
```yaml
base:
  role: "full_node"
  data_dir: "/opt/aptos/data"
  waypoint:
    from_file: "/opt/aptos/etc/waypoint.txt"

execution:
  genesis_file_location: "/opt/aptos/etc/genesis.blob"

full_node_networks:
  - network_id: "public"
    discovery_method: "onchain"
    listen_address: "/ip4/0.0.0.0/tcp/6182"
    max_inbound_connections: 100

mempool:
  shared_mempool_max_concurrent_inbound_syncs: 16 # default 4
  max_broadcasts_per_peer: 4 # default 1
  default_failovers: 0 # default 3
  shared_mempool_batch_size: 200 # default 100
  shared_mempool_tick_interval_ms: 10 # default 50

api:
  enabled: true
  address: "0.0.0.0:8080"
  max_transactions_page_size: 65535
  max_events_page_size: 65535

storage:
  enable_indexer: true

state_sync:
  state_sync_driver:
    bootstrapping_mode: ApplyTransactionOutputsFromGenesis
    continuous_syncing_mode: ApplyTransactionOutputs
```

**Comment by JoshLind** [comment]
> The fullnode is started on 2022-10, and that time we choose the aptoslabs/validator:mainnet_9e7800f46230d10c805129c49cb9ed528a40e25b image version.

Aah, that's the issue. You need to update. That image is 2 versions out of date. Can you update and see if it solves your problem?

**Comment by Alivers** [comment]
> > The fullnode is started on 2022-10, and that time we choose the aptoslabs/validator:mainnet_9e7800f46230d10c805129c49cb9ed528a40e25b image version.
> 
> Aah, that's the issue. You need to update. That image is 2 versions out of date. Can you update and see if it solves your problem?

Thanks! I  had updated the image to `aptos-node-v1.2.5` and things look fine. The fullnode ledger  version has caught up.

**Comment by AliNawaz-777** [comment]
How to fixed this issue in **PartialVMError with status UNKNOWN_VERSION** in StarCoin BlockChain
