### ISSUE TITLE
[Bug] Full node stopped working due to invalid proof for StateKey

### ISSUE THREAD

**Issue by ppoliani** [aptos-labs/aptos-core#7985]
# 🐛 Bug

The started suddenly panicking with the following error.

```
2023-04-29T21:42:10.569449Z [kv_reader_27] ERROR crates/crash-handler/src/lib.rs:41 details = '''panicked at 'Must succeed.: Proof is invalid for key StateKey { inner: AccessPath(AccessPath { address: 0000000000000000000000000000000000000000000000000000000000000001, path: 01000000000000000000000000000000000000000000000000000000000000000105626c6f636b0d426c6f636b5265736f7572636500 }), hash: OnceCell(HashValue(5ddf404c60e96e9485beafcabb95609fed8e38e941a725cae4dcec8296fb32d7)) } with state root hash HashValue(a4782cc0615d7d1b6c42e2a465c86bfe5de79bc3b868cebaa5631485e0281f67): Value hashes do not match for key 5ddf404c60e96e9485beafcabb95609fed8e38e941a725cae4dcec8296fb32d7. Value hash in proof: 0be5cd5091b4a83850ac601d88ba25f9a7d2f0a670e67d91a8e9e3106e053978. Expected value hash: e2f59ccd09c5c97967972e44a99842ff75f993b2aab422710700354b5a34775a. .', /code/aptos-core/storage/storage-interface/src/cached_state_view.rs:129:57'''
backtrace = '''
```

It stopped working at block `51413921`

I'm not quire sure what is the reason it's failing.

**Stack trace/error message**
```
    0x555becf19c06 - backtrace::backtrace::libunwind::trace::hfdb078f3c7dfc4ae
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::h111e07def32e76e7
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::hd3d5670e1160f40d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x555becf03541 - backtrace::capture::Backtrace::create::h126140a7b8886788
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::h869bfdd5d4d1cdb2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x555beafdbb24 - aptos_crash_handler::handle_panic::h73b7fb5cf46089eb
                               at /code/aptos-core/crates/crash-handler/src/lib.rs:37:38
                           aptos_crash_handler::setup_panic_handler::{{closure}}::h602e5969b8e5211a
                               at /code/aptos-core/crates/crash-handler/src/lib.rs:29:9
   3:     0x555bed0bff09 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbb63890df2a28e48
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:2001:9
                           std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:692:13
   4:     0x555bed0bfc87 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:579:13
   5:     0x555bed0be56c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
   6:     0x555bed0bf9a2 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   7:     0x555bed0e2763 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   8:     0x555bed0e2c73 - core::result::unwrap_failed::h065c02f906ca4578
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
   9:     0x555beb2db480 - core::result::Result<T,E>::expect::hab065e50add13027
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1070:23
                           aptos_storage_interface::cached_state_view::CachedStateView::prime_cache_by_write_set::{{closure}}::{{closure}}::{{closure}}::hfce845df67962aa5
                               at /code/aptos-core/storage/storage-interface/src/cached_state_view.rs:129:25
                           rayon_core::scope::Scope::spawn::{{closure}}::{{closure}}::h90601d8178aa0da9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/scope/mod.rs:544:47
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf985fa3a5eadba2c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panic/unwind_safe.rs:271:9
  10:     0x555beb300ee2 - std::panicking::try::do_call::h1224993e117ee997
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
                           std::panicking::try::hf2831fb4078a83f3
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
                           std::panic::catch_unwind::h9b2d489276929be1
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
                           rayon_core::unwind::halt_unwinding::h206b243cb9cb06ea
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/unwind.rs:17:5
                           rayon_core::scope::ScopeBase::execute_job_closure::h61e5dd3cb0960bed
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/scope/mod.rs:650:15
                           rayon_core::scope::ScopeBase::execute_job::h1034a8295a2bef01
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/scope/mod.rs:640:29
                           rayon_core::scope::Scope::spawn::{{closure}}::hb2fc332b843faa32
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/scope/mod.rs:544:17
                           <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::he62429d882890aa5
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/job.rs:167:9
  11:     0x555bec28dd88 - rayon_core::job::JobRef::execute::h7609226f3135bbba
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/job.rs:59:9
                           rayon_core::registry::WorkerThread::execute::h2ce17b6c29dbf140
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:752:9
                           rayon_core::registry::WorkerThread::wait_until_cold::h2e759545bbf5f379
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:729:17
  12:     0x555bec28c73e - rayon_core::registry::WorkerThread::wait_until::he8fca361cfbb8b2c
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:703:13
                           rayon_core::registry::main_loop::h1d167fc7ea3ea2ce
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:836:5
                           rayon_core::registry::ThreadBuilder::run::ha3dcb7260ec18b95
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:55:18
  13:     0x555bec2897e1 - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h57460fca896f2822
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.3/src/registry.rs:100:20
                           std::sys_common::backtrace::__rust_begin_short_backtrace::h0a3c07c70eeffc5a
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:121:18
  14:     0x555bec290990 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h8157166d73d3782a
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/mod.rs:551:17
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h27b3e19728629498
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panic/unwind_safe.rs:271:9
                           std::panicking::try::do_call::h9d78db6be0f9a5c7
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
                           std::panicking::try::hc7ea090d84afc79f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
                           std::panic::catch_unwind::h7ad73318a0e2508e
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
                           std::thread::Builder::spawn_unchecked_::{{closure}}::h840051acdbee4d16
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/mod.rs:550:30
                           core::ops::function::FnOnce::call_once{{vtable.shim}}::h49cc18cc8c2415ef
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
  15:     0x555bed0c37d3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6202d10b0224e7b0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
                           <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4dbea73c9cec160b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:1987:9
                           std::sys::unix::thread::Thread::new::thread_start::h0a2f4c32ba2f2278
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys/unix/thread.rs:108:17
```

## System information

aptos-node-v1.3.2
rustc 1.68.2
Ubuntu 22.10 x64

**Comment by grao1991** [comment]
Did you restart your node right before the crash, or it had been running for a while?

**Comment by grao1991** [comment]
This is an indication of data corruption (usually caused by hardware failure). You might need to resync your node.

**Comment by ppoliani** [comment]
Hey @grao1991 Thanks for getting back so quickly. 

> Did you restart your node right before the crash, or it had been running for a while?

It has been running for two weeks now. I did not restart it manually, no. The node is wrapped within a forever-like service which means that it will restart the node if the it stops running.

> This is an indication of data corruption (usually caused by hardware failure). You might need to resync your node and check your hardware.

Do you mean I should start syncing the node starting from the genesis block again? This is a very lengthy process which might take 2 days. Isn't there any way to start resyncing from some kind of checkpoint or snapshot?

With regards to hardware failure, I'm not quite sure what I can do so it doesn't happen again. I do follow the hardware requirements as stated [here](https://aptos.dev/nodes/validator-node/operator/node-requirements/). Is there anything else I should take care of?

**Comment by grao1991** [comment]
@ppoliani You can do fast sync if you don't need full ledger history. It basically downloads the latest state from the end of the previous epoch (every 2 hours), and replays all transactions after that. If your node can find an upstream peer close by, the sync should finish in 1~2 hours.
Another way is to use our public backup on gcp or AWS, @areshand can provide more details, or use a backup from our community (if you trust them, see https://aptos.dev/nodes/full-node/bootstrap-fullnode)

**Comment by grao1991** [comment]
@ppoliani I'm not sure whether/what issue your hardware has. Based on our team and some community operators experience, it could be RAM or DISK issue, and you can run some diagnostic tools to figure it out.

**Comment by ppoliani** [comment]
@grao1991 Thank you so much for your input. I'm running an indexer so I do need every single transaction; so unfortunately  I guess I'll have to re-sync the full node again :(

**Comment by areshand** [comment]
FYI, we are working on a tool to support restoring the DB from public backups. If you want to use it, we can let you know when it is available

**Comment by grao1991** [comment]
@ppoliani Can you share the most recent log with us?
