### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Lredhdx** [aptos-labs/aptos-core#8912]
# 🐛 Bug

## To reproduce

**Code snippet to reproduce**
1. install the indexer(commit-id: [f43ce08](https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.5.1))
2. run the token indexer in mainnet
3. it will panic and stuck when indexing version 168782621(the version was got from error log, see blow)
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
2023-06-30T09:00:51.868506Z [sync-driver-3] INFO state-sync/state-sync-v2/state-sync-driver/src/storage_synchronizer.rs:456 {"message":"Applied a new transaction output chunk! Transaction total: 12.","name":"storage_synchronizer"}
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/mod.rs:91:19
  11:     0x560fda754585 - <core::pin::Pin<P> as core::future::future::Future>::poll::h9ccf9f098dee4a54
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/future.rs:124:9
                           aptos_indexer::indexer::transaction_processor::TransactionProcessor::process_transactions_with_status::{{closure}}::h6af2903f28a89707
                               at /usr/src/indexer-node/crates/indexer/src/indexer/transaction_processor.rs:84:13
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h8bb77156e8bd662c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/mod.rs:91:19
  12:     0x560fda759756 - <core::pin::Pin<P> as core::future::future::Future>::poll::h9ccf9f098dee4a54
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/future.rs:124:9
                           aptos_indexer::indexer::tailer::Tailer::process_next_batch::{{closure}}::h9ecc467eaf344336
                               at /usr/src/indexer-node/crates/indexer/src/indexer/tailer.rs:153:13
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcc05b63ef8103b95
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/mod.rs:91:19
                           aptos_indexer::runtime::run_forever::{{closure}}::{{closure}}::ha3fa7b75e80943ad
                               at /usr/src/indexer-node/crates/indexer/src/runtime.rs:215:83
                           <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha92df85450a2fa67
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/future/mod.rs:91:19
  13:     0x560fda7d7024 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h50b8915ae2b669aa
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::haf497695de2b6db2
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
                           tokio::runtime::task::core::CoreStage<T>::poll::h25add5f4520f8fd5
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
                           tokio::runtime::task::harness::poll_future::{{closure}}::h90011789872499de
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3141e1873918158a
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panic/unwind_safe.rs:271:9
  14:     0x560fda7910e2 - std::panicking::try::do_call::h569d923394cd6df6
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
                           std::panicking::try::h96da68e7ef278341
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
                           std::panic::catch_unwind::hca8d19184bd4fc4e
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
                           tokio::runtime::task::harness::poll_future::h6434d3b64127cf59
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
2023-06-30T09:00:51.971326Z [indexer-2] ERROR crates/crash-handler/src/lib.rs:41 details = '''
panicked at 'called `Result::unwrap()` on an `Err` value: Failed to get collection creator for table handle 0xbb2d808a795e4384301ce6b442985c80dbddeacd4a3c73bf4a4db97ed57ea4df, txn version 168782621

Caused by:
    Failed to get collection creator', crates/indexer/src/models/token_models/tokens.rs:130:26'''
backtrace = '''
   0:     0x560fdb5b3d16 - backtrace::backtrace::libunwind::trace::h1e56b38ae1db3894
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
                           backtrace::backtrace::trace_unsynchronized::hba3a90c0e28417ff
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
                           backtrace::backtrace::trace::he3569da9cd8cfddb
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   1:     0x560fdb59d641 - backtrace::capture::Backtrace::create::hc5a4da796d4be649
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
                           backtrace::capture::Backtrace::new::hba93c373b59be48d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   2:     0x560fd93a90e4 - aptos_crash_handler::handle_panic::h537984001687c0b2
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:37:38
                           aptos_crash_handler::setup_panic_handler::{{closure}}::h3a07a66527e50d44
                               at /usr/src/indexer-node/crates/crash-handler/src/lib.rs:29:9
   3:     0x560fdb9445e9 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hbb63890df2a28e48
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/alloc/src/boxed.rs:2001:9
                           std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:692:13
   4:     0x560fdb944367 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:579:13
   5:     0x560fdb942c4c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
   6:     0x560fdb944082 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   7:     0x560fdb966ea3 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   8:     0x560fdb9673b3 - core::result::unwrap_failed::h065c02f906ca4578
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
                           tokio::runtime::task::harness::Harness<T,S>::poll_inner::he53c2de49c9f331d
   9:     0x560fda8c4e6e - core::result::Result<T,E>::unwrap::h03894543a76c847b
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1113:23
                           tokio::runtime::task::harness::Harness<T,S>::poll::hd29e30a16d74794b
                           aptos_indexer::models::token_models::tokens::Token::from_transaction::hff784017668a5e9a
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15
  15:     0x560fdb63eafa - tokio::runtime::task::raw::RawTask::poll::h1d05bc011492bf0a
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18
                           tokio::runtime::task::LocalNotified<S>::run::he28775ea1cb32154
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:385:9
                           tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h8074e8dfb784ca6d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:421:13
                           tokio::coop::with_budget::{{closure}}::hd600f709e9b7be3a
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
                           std::thread::local::LocalKey<T>::try_with::h0dc8d86533061fae
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/local.rs:446:16
                           std::thread::local::LocalKey<T>::with::hf0e6ffe1a09db0f3
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/local.rs:422:9
  16:     0x560fdb64ed25 - tokio::coop::with_budget::ha8b801032dd0a309
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5
                           tokio::coop::budget::hebcfe83319579290
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
                           tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h7ed8c038bc1f0643
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:420:9
  17:     0x560fdb64e55f - tokio::runtime::scheduler::multi_thread::worker::Context::run::h295f4f24debf2bf7
  18:     0x560fdb635277 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h8f179ca3b9eb7103
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:372:17
                           tokio::macros::scoped_tls::ScopedKey<T>::set::h9a97a3bbb0de242e
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/macros/scoped_tls.rs:61:9
  19:     0x560fdb64db72 - tokio::runtime::scheduler::multi_thread::worker::run::ha4ae1673b043c910
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:369:5
  20:     0x560fdb63d183 - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::h57ec794df155a34a
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:348:45
                           <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hbfa2d42fbda1e47f
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/blocking/task.rs:42:21
                           tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h57a74bacca226366
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
                           tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h246ffe36ac81d1fc
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
                           tokio::runtime::task::core::CoreStage<T>::poll::h65f54cfb0926d18c
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
  21:     0x560fdb64f83f - tokio::runtime::task::harness::poll_future::{{closure}}::h48ebcf0ac10417dd
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
                           <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4e7bb6905f1148bb
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panic/unwind_safe.rs:271:9
                               at /usr/src/indexer-node/crates/indexer/src/models/token_models/tokens.rs:123:25
                           std::panicking::try::do_call::h18a57d24ea9246c8
```

## Expected Behavior
It shouldn't panic and stuck there.

## System information

**Please complete the following information:**
- 
- 
-

**Comment by agafox** [comment]
@Lredhdx I'm having the same issue. What was your resolution?
